import React, { createContext, useContext, useState, useCallback, useEffect } from 'react';

export type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// French translations (primary)
const fr: Record<string, string> = {
  // Header
  'nav.individuals': 'Particuliers',
  'nav.professionals': 'Professionnels',
  'nav.lifeAndSavings': 'Vie & Épargne',
  'nav.realEstate': 'Immobilier',
  'nav.aboutUs': 'Qui sommes-nous ?',
  'nav.partners': 'Nos Partenaires',
  'nav.reviews': 'Avis Clients',
  'nav.blog': 'Blog',
  'nav.openMenu': 'Ouvrir le menu',
  'nav.closeMenu': 'Fermer le menu',
  'nav.back': 'Retour',
  'nav.share': 'Partager',
  'nav.favorites': 'Favoris',
  'nav.print': 'Imprimer',
  'nav.moreActions': "Plus d'actions",
  
  // Insurance types
  'insurance.auto': 'Auto',
  'insurance.moto': 'Moto',
  'insurance.home': 'Habitation',
  'insurance.health': 'Santé',
  'insurance.pets': 'Animaux',
  'insurance.rcPro': 'RC Pro',
  'insurance.mrp': 'MRP',
  'insurance.life': 'Assurance Vie',
  'insurance.loan': 'Assurance de Prêt',
  'insurance.provident': 'Prévoyance',
  'insurance.gli': 'Garantie Loyer Impayée',
  'insurance.pno': 'PNO',
  'insurance.rentalManagement': 'Gestion Locative',
  
  // Hero
  'hero.title': 'Le site pour trouver son assurance moins chère,',
  'hero.titleHighlight': 'sans compromis.',
  'hero.subtitle': 'Comparez',
  'hero.subtitleBold': '50+ assureurs',
  'hero.subtitleEnd': 'en 2 minutes.',
  'hero.subtitleSecondary': 'Gratuit et sans engagement.',
  'hero.savingsBadge': "Économisez jusqu'à",
  'hero.savingsPercent': '40%',
  'hero.savingsEnd': 'sur votre assurance actuelle',
  'hero.arthurSpeech': "Moi c'est Arthur !",
  'hero.partnersCount': 'Assureurs partenaires',
  'hero.compareTime': 'Comparaison express',
  'hero.freeLabel': 'Gratuit & sans engagement',
  
  // Categories
  'category.auto': 'Auto',
  'category.moto': 'Moto',
  'category.home': 'Habitation',
  'category.health': 'Santé',
  'category.pets': 'Animaux',
  'category.life': 'Vie',
  
  // Features
  'features.title': 'Pourquoi nous choisir ?',
  'features.subtitle': 'Des avantages exclusifs pour vous accompagner',
  'features.free.title': '100% Gratuit',
  'features.free.description': 'Notre service de comparaison est entièrement gratuit et sans engagement.',
  'features.fast.title': 'Rapide & Simple',
  'features.fast.description': 'Obtenez vos devis en moins de 2 minutes.',
  'features.expert.title': 'Experts Dédiés',
  'features.expert.description': 'Une équipe de conseillers disponible pour vous accompagner.',
  'features.secure.title': 'Données Sécurisées',
  'features.secure.description': 'Vos informations sont protégées et confidentielles.',
  
  // FAQ
  'faq.title': 'Questions Fréquentes',
  'faq.subtitle': 'Tout ce que vous devez savoir sur notre comparateur',
  
  // Footer
  'footer.tagline': "Arthur, votre super-héros des économies d'assurance.",
  'footer.insurances': 'Nos Assurances',
  'footer.about': 'À propos',
  'footer.info': 'Informations',
  'footer.cookies': 'Cookies',
  'footer.legal': 'Mentions légales',
  'footer.terms': 'CGU',
  'footer.privacy': 'Confidentialité',
  'footer.contact': 'Contact',
  'footer.sitemap': 'Plan du site',
  'footer.newsletter': 'Newsletter',
  'footer.rights': 'Tous droits réservés',
  'footer.privacyCharter': 'Charte de Confidentialité',
  'footer.securePayment': 'Paiement Sécurisé',
  'footer.gdprProtected': 'Données Protégées RGPD',
  'footer.verifiedSite': 'Site Vérifié',
  'footer.disclaimer': 'Jemassuremoinscher.fr est un comparateur indépendant. Les tarifs affichés sont indicatifs et peuvent varier selon votre profil. Ce site ne se substitue pas aux conseils d\'un professionnel de l\'assurance.',
  'footer.description': 'Comparez les meilleures assurances en France. Gratuit, rapide et sans engagement.',
  'footer.legalSection': 'Légal',
  'footer.privacyPolicy': 'Politique de confidentialité',
  'footer.cookiePolicy': 'Politique cookies',
  
  // Testimonials
  'testimonials.title': 'Ils nous font confiance',
  'testimonials.subtitle': 'Découvrez les avis de nos clients satisfaits qui ont économisé sur leurs assurances',
  'testimonials.avgRating': 'Note moyenne',
  'testimonials.satisfiedClients': 'Clients satisfaits',
  'testimonials.satisfactionRate': 'Taux de satisfaction',
  'testimonials.avgSavings': 'Économie moyenne',
  'testimonials.t1.text': "J'ai économisé 450€ sur mon assurance auto en quelques clics ! Le service est rapide et les offres sont vraiment compétitives. Je recommande vivement.",
  'testimonials.t1.insurance': 'Assurance Auto',
  'testimonials.t2.text': "Excellent comparateur ! J'ai trouvé une assurance habitation 30% moins chère que mon ancienne. Le processus est simple et sans engagement.",
  'testimonials.t2.insurance': 'Assurance Habitation',
  'testimonials.t3.text': "Très satisfaite ! En 2 minutes j'ai comparé plusieurs mutuelles santé et j'ai trouvé celle qui correspond parfaitement à mes besoins. Un vrai gain de temps.",
  'testimonials.t3.insurance': 'Assurance Santé',
  'testimonials.t4.text': "Service efficace et gratuit. J'ai pu comparer toutes les assurances moto du marché facilement. Les conseillers sont disponibles si besoin.",
  'testimonials.t4.insurance': 'Assurance Moto',
  'testimonials.t5.text': "Je ne pensais pas économiser autant sur mon assurance de prêt ! Le comparateur m'a fait gagner plus de 800€ par an. Merci !",
  'testimonials.t5.insurance': 'Assurance Prêt',
  'testimonials.t6.text': "Parfait pour trouver la meilleure assurance pour mon chien. Les tarifs sont transparents et j'ai reçu mon devis instantanément.",
  'testimonials.t6.insurance': 'Assurance Animaux',
  
  // Partners
  'partners.title': 'Nos Partenaires',
  'partners.subtitle': 'Plus de 120 assureurs de confiance',
  
  // Common
  'common.learnMore': 'En savoir plus',
  'common.getQuote': 'Obtenir un devis',
  'common.compare': 'Comparer',
  'common.free': 'Gratuit',
  'common.close': 'Fermer',
  'common.loading': 'Chargement en cours...',
  'common.back': 'Retour',
  'common.continue': 'Continuer',
  'common.send': 'Envoyer',
  'common.readMore': 'Lire la suite',
  'common.advice': 'Conseil',
  'common.cancel': 'Annuler',
  'common.confirm': 'Confirmer',
  'common.sending': 'Envoi...',
  'common.perMonth': 'par mois',
  'common.perYear': 'par an',
  
  // How it works
  'howItWorks.title': 'Comment ça marche ?',
  'howItWorks.subtitle': "Comparer ses assurances n'a jamais été aussi simple",
  'howItWorks.step1.title': 'Je remplis mon profil',
  'howItWorks.step1.description': 'En 2 minutes, décrivez vos besoins en assurance.',
  'howItWorks.step2.title': 'Je compare les offres',
  'howItWorks.step2.description': 'Arthur analyse 50+ assureurs pour vous.',
  'howItWorks.step3.title': 'On me rappelle tout de suite',
  'howItWorks.step3.description': 'Choisissez la meilleure offre et faites-vous rappeler.',
  'howItWorks.arthurCta': "s'occupe de tout !",
  
  // Why us
  'whyUs.title': 'Pourquoi nous choisir ?',
  'whyUs.subtitle': 'Découvrez ce qui nous différencie des autres comparateurs',
  'whyUs.criteria': 'Critères',
  'whyUs.others': 'Autres comparateurs',
  'whyUs.othersMobile': 'Autres',
  'whyUs.speed': 'Rapidité',
  'whyUs.speedUs': 'Devis en 2 minutes',
  'whyUs.speedThem': "Jusqu'à 15 minutes",
  'whyUs.insurerCount': "Nombre d'assureurs",
  'whyUs.insurerCountUs': '50+ partenaires',
  'whyUs.insurerCountThem': '10-20 assureurs',
  'whyUs.transparency': 'Transparence des prix',
  'whyUs.transparencyUs': 'Prix affichés sans surprise',
  'whyUs.transparencyThem': 'Frais cachés fréquents',
  'whyUs.mascot': 'Mascotte préférée',
  'whyUs.mascotUs': 'Arthur, le super-héros !',
  'whyUs.mascotThem': 'Aucune mascotte 😢',
  'whyUs.didYouKnow': 'Saviez-vous que',
  'whyUs.9outOf10': '9 clients sur 10',
  'whyUs.save': 'économisent',
  'whyUs.perYear': 'par an',
  'whyUs.googleReviews': 'sur Google Reviews • +250 avis',
  'whyUs.service100': 'Service 100%',
  'whyUs.freeService': 'Gratuit',
  'whyUs.data': 'Données',
  'whyUs.secured': 'Sécurisées',
  'whyUs.arthurSays': 'Arthur vous dit :',
  'whyUs.arthurQuote': '"Je négocie pour vous les',
  'whyUs.bestRates': 'meilleurs tarifs',
  
  // SEO FAQ
  'seoFaq.title': 'Questions fréquentes',
  'seoFaq.subtitle': "Tout ce que vous devez savoir sur la comparaison d'assurances",
  'seoFaq.q1': 'Comment économiser sur mon assurance auto ?',
  'seoFaq.a1': "Pour économiser sur votre assurance auto, comparez les offres de plusieurs assureurs grâce à notre comparateur gratuit. Analysez les garanties proposées, ajustez votre franchise, et profitez des réductions pour bon conducteur. En moyenne, nos utilisateurs économisent 320€ par an sur leur assurance auto.",
  'seoFaq.q2': 'Est-ce vraiment gratuit ?',
  'seoFaq.a2': "Oui, notre service de comparaison est 100% gratuit et sans engagement. Nous sommes rémunérés par les assureurs partenaires uniquement si vous souscrivez à une offre. Vous ne payez jamais de frais supplémentaires pour utiliser notre comparateur.",
  'seoFaq.q3': "Puis-je changer d'assurance n'importe quand ?",
  'seoFaq.a3': "Depuis la loi Hamon de 2015, vous pouvez résilier votre contrat d'assurance auto, moto ou habitation à tout moment après la première année de souscription. Pour l'assurance santé, la résiliation est possible à la date d'anniversaire du contrat avec un préavis de 2 mois, ou à tout moment après la première année grâce à la résiliation infra-annuelle.",
  'seoFaq.moreQuestions': "D'autres questions ?",
  'seoFaq.arthurHere': 'est là pour vous !',
  
  // Quick Quote
  'quickQuote.srTitle': "Simulateur d'assurance auto et santé",
  'quickQuote.title': 'Mon Devis Rapide',
  'quickQuote.subtitle': 'Arthur calcule votre économie en 30 secondes',
  'quickQuote.vehicleQuestion': 'Quel est votre véhicule ?',
  'quickQuote.ageQuestion': 'Quel est votre âge ?',
  'quickQuote.contactQuestion': 'Vos coordonnées pour le devis',
  'quickQuote.emailLabel': 'Votre email',
  'quickQuote.phoneLabel': 'Votre téléphone',
  'quickQuote.privacyNote': "Un expert vous rappelle pour vous proposer le meilleur tarif. Vos données sont protégées et ne seront jamais partagées.",
  'quickQuote.submit': 'Recevoir mon devis',
  'quickQuote.sending': 'Envoi en cours...',
  'quickQuote.successTitle': 'Demande envoyée !',
  'quickQuote.successText': 'Un expert vous rappelle dans les',
  'quickQuote.successTime': '2 heures',
  'quickQuote.successEnd': 'pour vous proposer le meilleur tarif.',
  'quickQuote.successCheck': 'Vérifiez votre téléphone et votre email.',
  'quickQuote.secureData': '🔒 Vos données sont sécurisées et confidentielles',
  'quickQuote.citadine': 'Citadine',
  'quickQuote.citadineDesc': 'Petite voiture de ville',
  'quickQuote.berline': 'Berline',
  'quickQuote.berlineDesc': 'Confort et espace',
  'quickQuote.suv': 'SUV / 4x4',
  'quickQuote.suvDesc': 'Tout-terrain',
  'quickQuote.toastSuccess': 'Demande envoyée ! Nous vous contactons très vite.',
  'quickQuote.toastError': 'Erreur. Veuillez réessayer.',
  
  // Guides
  'guides.mainTitle': 'Tout savoir pour payer moins cher',
  'guides.mainSubtitle': "Arthur partage ses meilleurs conseils pour optimiser vos contrats d'assurance",
  'guides.arthurSpeech': 'À lire ! 📚',
  'guides.cta': 'Lancer mon comparatif gratuit',
  'guides.article1.title': 'Loi Hamon : comment résilier ?',
  'guides.article1.excerpt': "Résiliez votre assurance à tout moment après 1 an de contrat.",
  'guides.article2.title': '5 astuces pour réduire sa prime',
  'guides.article2.excerpt': "Découvrez nos conseils d'experts pour économiser jusqu'à 40%.",
  'guides.article3.title': 'Jeune conducteur : quel budget ?',
  'guides.article3.excerpt': "Guide complet pour assurer votre première voiture au meilleur prix.",
  
  // Sticky CTA
  'stickyCta.text': 'Lancer mon comparatif gratuitement',
  
  // Insurance labels for footer
  'footer.autoInsurance': 'Assurance Auto',
  'footer.motoInsurance': 'Assurance Moto',
  'footer.homeInsurance': 'Assurance Habitation',
  'footer.healthInsurance': 'Assurance Santé',
  'footer.petInsurance': 'Assurance Animaux',
  'footer.lifeInsurance': 'Assurance Vie',
  'footer.whoAreWe': 'Qui sommes-nous ?',
  'footer.ourPartners': 'Nos partenaires',
  
  // Pages
  'page.blog.title': 'Blog',
  'page.blog.subtitle': 'Conseils et actualités assurance',
  'page.about.title': 'Qui sommes-nous ?',
  'page.about.subtitle': 'Découvrez notre histoire et notre mission',
  'page.partners.title': 'Nos Partenaires',
  'page.partners.subtitle': 'Découvrez nos assureurs partenaires',
  'page.contact.title': 'Contactez-nous',
  'page.contact.subtitle': 'Notre équipe est à votre écoute',

  // Savings Calculator
  'calc.title': 'Calculez vos',
  'calc.titleHighlight': 'économies potentielles',
  'calc.subtitle': "Découvrez combien vous pourriez économiser en changeant d'assurance",
  'calc.yourInfo': 'Vos informations',
  'calc.insuranceType': "Type d'assurance",
  'calc.autoIns': 'Assurance Auto',
  'calc.motoIns': 'Assurance Moto',
  'calc.homeIns': 'Assurance Habitation',
  'calc.healthIns': 'Mutuelle Santé',
  'calc.currentPrice': 'Prix actuel mensuel (€)',
  'calc.yourAge': 'Votre âge',
  'calc.vehicleAge': 'Âge du véhicule (années)',
  'calc.calculate': 'Calculer mes économies',
  'calc.potentialSavings': 'Vos économies potentielles',
  'calc.fillForm': 'Remplissez le formulaire pour voir vos économies potentielles',
  'calc.currentPriceLabel': 'Prix actuel',
  'calc.estimatedPrice': 'Prix estimé',
  'calc.savings': "d'économies",
  'calc.monthlySaving': 'Économie mensuelle',
  'calc.annualSaving': 'Économie annuelle',
  'calc.vacationMsg': 'ans, vous aurez économisé de quoi partir en vacances ! 🏖️',
  'calc.compareNow': 'Comparer les offres maintenant',
  'calc.disclaimer': '* Estimation basée sur les économies moyennes constatées. Les économies réelles peuvent varier selon votre profil.',

  // Quote Request Form
  'quoteForm.title': 'Demandez votre',
  'quoteForm.titleHighlight': 'devis gratuit',
  'quoteForm.subtitle': 'Remplissez ce formulaire et recevez votre devis personnalisé en 24h',
  'quoteForm.insuranceType': "Type d'assurance *",
  'quoteForm.selectType': 'Sélectionnez un type',
  'quoteForm.autoIns': 'Assurance Auto',
  'quoteForm.motoIns': 'Assurance Moto',
  'quoteForm.homeIns': 'Assurance Habitation',
  'quoteForm.healthIns': 'Mutuelle Santé',
  'quoteForm.loanIns': 'Assurance Prêt',
  'quoteForm.petIns': 'Assurance Animaux',
  'quoteForm.fullName': 'Nom complet *',
  'quoteForm.email': 'Email *',
  'quoteForm.phone': 'Téléphone *',
  'quoteForm.postalCode': 'Code postal *',
  'quoteForm.currentInsurer': 'Assureur actuel (optionnel)',
  'quoteForm.acceptTerms': "J'accepte les conditions générales et la politique de confidentialité *",
  'quoteForm.submit': 'Obtenir mon devis gratuit',
  'quoteForm.submitting': 'Envoi en cours...',
  'quoteForm.required': '* Champs obligatoires. Vos données sont sécurisées et ne seront jamais partagées.',
  'quoteForm.successTitle': 'Demande envoyée avec succès !',
  'quoteForm.successText': 'Votre demande de devis a bien été enregistrée. Un de nos conseillers vous contactera dans les 24 heures pour vous proposer les meilleures offres adaptées à votre profil.',
  'quoteForm.newRequest': 'Faire une nouvelle demande',
  'quoteForm.toastSuccess': 'Demande envoyée !',
  'quoteForm.toastSuccessDesc': 'Nous vous contacterons dans les 24h avec votre devis personnalisé.',
  'quoteForm.toastError': 'Erreur',
  'quoteForm.toastErrorDesc': 'Une erreur est survenue. Veuillez réessayer.',

  // Insurance Comparison
  'comparison.title': 'Comparaison des offres',
  'comparison.subtitle': 'Voici les 10 meilleures offres pour votre profil',
  'comparison.bestOffer': 'Meilleure offre',
  'comparison.callbackBtn': 'Me faire rappeler',
  'comparison.newRequest': 'Faire une nouvelle demande',

  // Insurance FAQ
  'insuranceFaq.defaultTitle': 'Questions fréquentes',

  // Cookie Banner
  'cookies.title': 'Gestion des cookies',
  'cookies.description': 'Nous utilisons des cookies pour améliorer votre expérience',
  'cookies.text': 'Nous utilisons des cookies pour personnaliser le contenu et les annonces, pour fournir des fonctionnalités de médias sociaux et pour analyser notre trafic. Vous pouvez accepter tous les cookies ou gérer vos préférences.',
  'cookies.learnMore': 'En savoir plus',
  'cookies.acceptAll': 'Tout accepter',
  'cookies.rejectAll': 'Tout refuser',
  'cookies.customize': 'Personnaliser',
  'cookies.necessary': 'Cookies nécessaires',
  'cookies.necessaryDesc': 'Essentiels au fonctionnement du site. Toujours activés.',
  'cookies.analytics': 'Cookies analytiques',
  'cookies.analyticsDesc': 'Nous aident à comprendre comment vous utilisez notre site.',
  'cookies.marketing': 'Cookies marketing',
  'cookies.marketingDesc': 'Utilisés pour afficher des publicités pertinentes.',
  'cookies.savePreferences': 'Enregistrer mes préférences',

  // Interactive Comparator
  'comparator.badge': 'Comparateur en Temps Réel',
  'comparator.heroTitle': 'Découvrez vos économies potentielles',
  'comparator.heroSubtitle': 'Comparez instantanément les meilleures offres du marché',
  'comparator.insuranceType': "Type d'assurance",
  'comparator.autoIns': '🚗 Assurance Auto',
  'comparator.motoIns': '🏍️ Assurance Moto',
  'comparator.homeIns': '🏠 Assurance Habitation',
  'comparator.healthIns': '💊 Mutuelle Santé',
  'comparator.sortBy': 'Trier par',
  'comparator.bestSavings': '💰 Meilleures économies',
  'comparator.lowestPrice': '💵 Prix le plus bas',
  'comparator.bestRating': '⭐ Meilleure note',
  'comparator.currentPrice': 'Votre prix actuel',
  'comparator.yearlySavings': 'Économie potentielle sur 1 an',
  'comparator.switchingTo': 'En passant à notre meilleure offre à',
  'comparator.offersAvailable': 'offres disponibles',
  'comparator.share': 'Partager',
  'comparator.bestOfferBadge': 'Meilleure offre',
  'comparator.popular': '⭐ Populaire',
  'comparator.callbackBtn': 'Me faire rappeler',
  'comparator.needHelp': "Besoin d'aide pour choisir ?",
  'comparator.expertHelp': 'Nos experts comparent gratuitement toutes les offres et vous conseillent la meilleure solution',
  'comparator.talkExpert': 'Parler à un expert gratuitement',
  'comparator.linkCopied': 'Lien copié !',

  // Subscription Modal
  'subModal.title': 'Demande de rappel',
  'subModal.fullName': 'Nom complet *',
  'subModal.email': 'Email *',
  'subModal.phone': 'Téléphone *',
  'subModal.acceptTerms': "J'accepte les conditions générales et la politique de confidentialité *",
  'subModal.successTitle': 'Demande envoyée !',
  'subModal.successText': 'Nous vous contactons dans les 24h pour vous accompagner.',
  'subModal.toastSuccess': 'Demande envoyée avec succès !',
  'subModal.toastError': 'Une erreur est survenue. Veuillez réessayer.',

  // Trust Badges
  'trust.secureData': 'Données sécurisées',
  'trust.secureDataDesc': 'Conformité RGPD',
  'trust.certified': 'Certifié qualité',
  'trust.certifiedDesc': 'Service vérifié',
  'trust.securePay': 'Paiements sécurisés',
  'trust.securePayDesc': 'SSL/TLS',
  'trust.clients': '+50 000 clients',
  'trust.clientsDesc': 'Nous font confiance',
  'trust.savingsGuaranteed': 'Économies garanties',
  'trust.savingsGuaranteedDesc': 'Ou remboursé',
  'trust.noCommitment': 'Sans engagement',
  'trust.noCommitmentDesc': '100% gratuit',

  // NotFound
  'notFound.title': '404',
  'notFound.text': 'Oops ! Page introuvable',
  'notFound.link': "Retour à l'accueil",

  // Insurance Pages Common
  'insPage.compareNow': 'Comparer maintenant',
  'insPage.getQuote': 'Obtenez votre devis personnalisé',
  'insPage.loading': 'Envoi en cours...',
  'insPage.compareOffers': 'Comparer les offres',
  'insPage.learnMore': 'En savoir plus sur',
  'insPage.faqTitle': 'Questions fréquentes',
  'insPage.readyToSave': 'Prêt à économiser sur votre',
  'insPage.compareFree': 'Comparez gratuitement les meilleures offres en 2 minutes.',
  'insPage.compareNowBtn': 'Comparer les offres maintenant',
  'insPage.quoteIn2min': 'Devis en 2 minutes',
  'insPage.quoteIn2minDesc': 'Simple, rapide et 100% gratuit.',
  'insPage.select': 'Sélectionner',
  'insPage.postalCode': 'Code postal',
  'insPage.yourAge': 'Votre âge',

  // Auto Page
  'autoPage.title': 'Assurance Auto',
  'autoPage.subtitle': "Comparez les meilleures offres et économisez jusqu'à 400€ par an.",
  'autoPage.adv1.title': "Jusqu'à 400€ d'économies",
  'autoPage.adv1.desc': 'Comparez et économisez sur votre assurance auto.',
  'autoPage.adv2.desc': "Les meilleures offres du marché.",
  'autoPage.adv2.title': '20+ assureurs comparés',
  'autoPage.form.brand': 'Marque du véhicule',
  'autoPage.form.brandPlaceholder': 'Sélectionner une marque',
  'autoPage.form.model': 'Modèle',
  'autoPage.form.modelPlaceholder': 'Entrez le modèle',
  'autoPage.form.modelFirst': "Sélectionnez d'abord une marque",
  'autoPage.form.modelSelect': 'Sélectionner un modèle',
  'autoPage.form.year': 'Année',
  'autoPage.form.fuel': 'Carburant',
  'autoPage.form.fuel.essence': 'Essence',
  'autoPage.form.fuel.diesel': 'Diesel',
  'autoPage.form.fuel.electric': 'Électrique',
  'autoPage.form.fuel.hybrid': 'Hybride',
  'autoPage.form.license': "Date d'obtention du permis",
  'autoPage.form.bonusMalus': 'Coefficient Bonus-Malus',
  'autoPage.form.bonusMalusPlaceholder': 'Sélectionner votre coefficient',
  'autoPage.form.bonus050': '0.50 (Bonus maximal)',
  'autoPage.form.bonus060': '0.60 (9 ans sans sinistre)',
  'autoPage.form.bonus070': '0.70 (6 ans sans sinistre)',
  'autoPage.form.bonus080': '0.80 (3 ans sans sinistre)',
  'autoPage.form.bonus090': '0.90 (1 an sans sinistre)',
  'autoPage.form.bonus100': '1.00 (Coefficient de référence)',
  'autoPage.form.bonus125': '1.25 (1 sinistre responsable)',
  'autoPage.form.bonus150': '1.50 (2+ sinistres)',
  'autoPage.form.other': 'Autre',
  'autoPage.learnMore': "l'assurance auto",
  'autoPage.readyToSave': 'assurance auto',
  'autoPage.faq1.q': "Quelle est la différence entre une assurance au tiers et tous risques ?",
  'autoPage.faq1.a': "L'assurance au tiers couvre uniquement les dommages causés aux tiers. L'assurance tous risques offre une protection complète incluant les dommages à votre propre véhicule.",
  'autoPage.faq2.q': "Comment est calculé le prix de mon assurance auto ?",
  'autoPage.faq2.a': "Le tarif dépend de votre âge, ancienneté de permis, historique de sinistres, type de véhicule et lieu de résidence.",
  'autoPage.faq3.q': "Puis-je résilier mon assurance auto à tout moment ?",
  'autoPage.faq3.a': "Oui, depuis la loi Hamon, vous pouvez résilier après un an d'engagement, sans frais ni pénalités.",
  'autoPage.faq4.q': "Qu'est-ce que le bonus-malus ?",
  'autoPage.faq4.a': "C'est un coefficient qui fait varier votre prime selon votre historique de conduite. Sans accident, vous gagnez 5% de bonus par an.",

  // Santé Page
  'santePage.title': 'Mutuelle Santé',
  'santePage.subtitle': "Comparez les meilleures mutuelles et économisez jusqu'à 300€ par an.",
  'santePage.adv1.title': "Jusqu'à 300€ d'économies",
  'santePage.adv1.desc': 'Comparez et économisez sur votre mutuelle santé.',
  'santePage.adv2.title': '20+ mutuelles comparées',
  'santePage.adv2.desc': "Les meilleures offres du marché.",
  'santePage.form.situation': 'Situation familiale',
  'santePage.form.single': 'Célibataire',
  'santePage.form.couple': 'En couple',
  'santePage.form.family': 'Famille',
  'santePage.form.regime': 'Régime de sécurité sociale',
  'santePage.form.regimeGeneral': 'Régime général',
  'santePage.form.alsace': 'Alsace-Moselle',
  'santePage.form.tns': 'TNS',
  'santePage.form.agricole': 'Agricole',
  'santePage.form.level': 'Niveau de couverture souhaité',
  'santePage.form.economique': 'Économique',
  'santePage.form.equilibre': 'Équilibré',
  'santePage.form.confort': 'Confort',
  'santePage.form.premium': 'Premium',
  'santePage.learnMore': 'la mutuelle santé',
  'santePage.readyToSave': 'mutuelle santé',
  'santePage.faq1.q': "Quelle est la différence entre mutuelle et complémentaire santé ?",
  'santePage.faq1.a': "Les deux termes désignent la même chose : un contrat qui complète les remboursements de la Sécurité sociale pour vos frais de santé.",
  'santePage.faq2.q': 'Comment fonctionne le remboursement ?',
  'santePage.faq2.a': "Après prise en charge par la Sécu, votre mutuelle rembourse le reste à charge selon les garanties de votre contrat (100%, 200%, etc. de la base Sécu).",
  'santePage.faq3.q': 'Puis-je changer de mutuelle à tout moment ?',
  'santePage.faq3.a': "Oui, après un an d'engagement, vous pouvez résilier sans frais ni justification grâce à la loi du 14 juillet 2019.",
  'santePage.faq4.q': "Qu'est-ce que le 100% Santé ?",
  'santePage.faq4.a': "Le 100% Santé permet d'accéder à des lunettes, prothèses dentaires et aides auditives sans reste à charge, si votre mutuelle est responsable.",

  // Habitation Page
  'habitationPage.title': 'Assurance Habitation',
  'habitationPage.subtitle': "Comparez les meilleures offres et économisez jusqu'à 300€ par an.",
  'habitationPage.adv1.title': "Jusqu'à 300€ d'économies",
  'habitationPage.adv1.desc': 'Comparez et économisez sur votre assurance habitation.',
  'habitationPage.adv2.title': '20+ assureurs comparés',
  'habitationPage.adv2.desc': "Les meilleures offres du marché.",
  'habitationPage.form.type': 'Type de logement',
  'habitationPage.form.house': 'Maison',
  'habitationPage.form.apartment': 'Appartement',
  'habitationPage.form.status': 'Vous êtes',
  'habitationPage.form.owner': 'Propriétaire',
  'habitationPage.form.tenant': 'Locataire',
  'habitationPage.form.surface': 'Surface (m²)',
  'habitationPage.form.rooms': 'Nombre de pièces',
  'habitationPage.form.room1': '1 pièce',
  'habitationPage.form.room2': '2 pièces',
  'habitationPage.form.room3': '3 pièces',
  'habitationPage.form.room4': '4 pièces',
  'habitationPage.form.room5': '5 pièces et +',
  'habitationPage.form.value': 'Valeur des biens à assurer (€)',
  'habitationPage.learnMore': "l'assurance habitation",
  'habitationPage.readyToSave': 'assurance habitation',
  'habitationPage.faq1.q': 'Quelles sont les garanties essentielles ?',
  'habitationPage.faq1.a': "Incendie, dégâts des eaux, vol, responsabilité civile et catastrophes naturelles sont les garanties de base.",
  'habitationPage.faq2.q': 'Dois-je assurer ma résidence secondaire ?',
  'habitationPage.faq2.a': "Ce n'est pas obligatoire sauf en copropriété, mais c'est fortement recommandé pour protéger votre patrimoine.",
  'habitationPage.faq3.q': 'Que faire en cas de sinistre ?',
  'habitationPage.faq3.a': "Déclarez le sinistre dans les 5 jours (2 jours pour un vol) auprès de votre assureur par courrier recommandé.",
  'habitationPage.faq4.q': "La franchise, c'est quoi ?",
  'habitationPage.faq4.a': "C'est le montant restant à votre charge après indemnisation. Plus la franchise est élevée, plus la prime est basse.",

  // Moto Page
  'motoPage.title': 'Assurance Moto',
  'motoPage.subtitle': "Comparez les meilleures offres et économisez jusqu'à 35% sur votre assurance moto.",
  'motoPage.adv1.title': "Jusqu'à 35% d'économies",
  'motoPage.adv1.desc': 'Comparez et économisez sur votre assurance moto.',
  'motoPage.adv2.title': '15+ assureurs comparés',
  'motoPage.adv2.desc': "Les meilleures offres du marché.",
  'motoPage.form.brand': 'Marque de la moto',
  'motoPage.form.brandPlaceholder': 'Ex: Yamaha, Honda...',
  'motoPage.form.model': 'Modèle',
  'motoPage.form.modelPlaceholder': 'Ex: MT-07, CBR...',
  'motoPage.form.type': 'Type de moto',
  'motoPage.form.roadster': 'Roadster',
  'motoPage.form.sportive': 'Sportive',
  'motoPage.form.custom': 'Custom',
  'motoPage.form.trail': 'Trail',
  'motoPage.form.scooter': 'Scooter',
  'motoPage.form.displacement': 'Cylindrée (cm³)',
  'motoPage.form.license': "Date d'obtention du permis",
  'motoPage.learnMore': "l'assurance moto",
  'motoPage.readyToSave': 'assurance moto',
  'motoPage.faq1.q': "Quelle est la différence entre assurance au tiers et tous risques ?",
  'motoPage.faq1.a': "L'assurance au tiers couvre les dommages causés aux tiers. Le tous risques inclut aussi les dommages à votre propre moto.",
  'motoPage.faq2.q': 'La garantie conducteur est-elle importante ?',
  'motoPage.faq2.a': "Oui, elle vous indemnise en cas de blessures, même si vous êtes responsable de l'accident.",
  'motoPage.faq3.q': 'Mon équipement est-il couvert ?',
  'motoPage.faq3.a': 'Certaines formules couvrent casque, blouson et gants. Vérifiez les plafonds de remboursement.',
  'motoPage.faq4.q': 'Puis-je assurer un scooter 50cc ?',
  'motoPage.faq4.a': "Oui, l'assurance est obligatoire pour tout véhicule à moteur, y compris les scooters 50cc.",

  // Animaux Page
  'animauxPage.title': 'Assurance Animaux',
  'animauxPage.subtitle': 'Protégez la santé de votre compagnon et maîtrisez vos dépenses vétérinaires.',
  'animauxPage.adv1.title': "Jusqu'à 100% remboursé",
  'animauxPage.adv1.desc': 'Les meilleurs taux de remboursement vétérinaire.',
  'animauxPage.adv2.title': '10+ assureurs comparés',
  'animauxPage.adv2.desc': 'Les meilleures mutuelles animaux.',
  'animauxPage.form.animalType': "Type d'animal",
  'animauxPage.form.dog': 'Chien',
  'animauxPage.form.cat': 'Chat',
  'animauxPage.form.breed': 'Race',
  'animauxPage.form.breedPlaceholder': 'Ex: Labrador, Siamois...',
  'animauxPage.form.animalAge': "Âge de l'animal",
  'animauxPage.form.sex': 'Sexe',
  'animauxPage.form.male': 'Mâle',
  'animauxPage.form.female': 'Femelle',
  'animauxPage.form.sterilized': 'Stérilisé/Castré',
  'animauxPage.form.yes': 'Oui',
  'animauxPage.form.no': 'Non',
  'animauxPage.learnMore': "l'assurance animaux",
  'animauxPage.readyToSave': 'compagnon',
  'animauxPage.readyTitle': 'Prêt à protéger votre compagnon ?',
  'animauxPage.readyDesc': 'Comparez gratuitement les meilleures mutuelles animaux en 2 minutes.',
  'animauxPage.faq1.q': "À partir de quel âge peut-on assurer son animal ?",
  'animauxPage.faq1.a': "Dès 2-3 mois jusqu'à 8-10 ans pour une première souscription.",
  'animauxPage.faq2.q': "Qu'est-ce que le délai de carence ?",
  'animauxPage.faq2.a': "Période après souscription pendant laquelle vous n'êtes pas couvert. Quelques jours pour les accidents, quelques mois pour les maladies.",
  'animauxPage.faq3.q': 'Les vaccins sont-ils remboursés ?',
  'animauxPage.faq3.a': 'Oui, avec les formules incluant un forfait prévention (vaccins, vermifuges, antiparasitaires).',
  'animauxPage.faq4.q': 'Que faire si mon animal a un problème de santé préexistant ?',
  'animauxPage.faq4.a': 'Les affections préexistantes sont généralement exclues. Souscrivez le plus tôt possible.',

  // Toast messages (shared across insurance pages)
  'insPage.toast.success': 'Offres générées !',
  'insPage.toast.successDesc': 'Consultez les meilleures offres pour votre profil.',
  'insPage.toast.successDescHome': 'Consultez les meilleures offres pour votre logement.',
  'insPage.toast.successDescMoto': 'Consultez les meilleures offres pour votre moto.',
  'insPage.toast.successDescPet': 'Consultez les meilleures offres pour votre animal.',
  'insPage.toast.error': 'Erreur',
  'insPage.toast.errorDesc': 'Une erreur est survenue. Veuillez réessayer.',

  // Vie Page
  'viePage.title': 'Assurance Vie',
  'viePage.subtitle': 'Constituez une épargne, préparez votre retraite ou protégez vos proches.',
  'viePage.adv1.title': 'Avantages fiscaux',
  'viePage.adv1.desc': 'Fiscalité attractive après 8 ans de détention.',
  'viePage.adv2.title': 'Capital protégé',
  'viePage.adv2.desc': 'Fonds euros sécurisés disponibles.',
  'viePage.form.capital': 'Capital souhaité (€)',
  'viePage.form.duration': 'Durée du contrat (années)',
  'viePage.form.type': "Type d'assurance vie",
  'viePage.form.epargne': 'Assurance vie épargne',
  'viePage.form.temporaire': 'Temporaire décès',
  'viePage.form.mixte': 'Contrat mixte',
  'viePage.form.health': 'État de santé',
  'viePage.form.excellente': 'Excellente',
  'viePage.form.bonne': 'Bonne',
  'viePage.form.moyenne': 'Moyenne',
  'viePage.form.fragile': 'Fragile',
  'viePage.form.smoker': 'Êtes-vous fumeur ?',
  'viePage.form.no': 'Non',
  'viePage.form.yes': 'Oui',
  'viePage.learnMore': "l'assurance vie",
  'viePage.ctaTitle': 'Prêt à faire fructifier votre épargne ?',
  'viePage.ctaDesc': "Comparez gratuitement les meilleurs contrats d'assurance vie.",
  'viePage.faq1.q': 'Quelle différence entre fonds euros et unités de compte ?',
  'viePage.faq1.a': 'Le fonds euros garantit votre capital. Les unités de compte offrent plus de rendement mais sans garantie.',
  'viePage.faq2.q': 'Peut-on retirer son argent à tout moment ?',
  'viePage.faq2.a': 'Oui, les rachats sont possibles à tout moment, avec une fiscalité avantageuse après 8 ans.',
  'viePage.faq3.q': 'Comment désigner les bénéficiaires ?',
  'viePage.faq3.a': 'Via la clause bénéficiaire du contrat. Elle peut être modifiée à tout moment.',

  // Prêt Page
  'pretPage.title': 'Assurance Prêt Immobilier',
  'pretPage.subtitle': "Économisez jusqu'à 50% sur votre assurance emprunteur grâce à la loi Lemoine.",
  'pretPage.adv1.title': "Jusqu'à 15 000€ d'économies",
  'pretPage.adv1.desc': 'Comparez et économisez sur votre assurance emprunteur.',
  'pretPage.adv2.title': 'Changement gratuit',
  'pretPage.adv2.desc': 'Loi Lemoine : résiliation à tout moment.',
  'pretPage.adv3.title': 'Garanties équivalentes',
  'pretPage.adv3.desc': 'Même protection, prix réduit.',
  'pretPage.form.amount': 'Montant du prêt (€)',
  'pretPage.form.duration': 'Durée du prêt',
  'pretPage.form.status': 'Statut professionnel',
  'pretPage.form.salarie': 'Salarié',
  'pretPage.form.fonctionnaire': 'Fonctionnaire',
  'pretPage.form.independant': 'Indépendant',
  'pretPage.form.profRisk': 'Profession à risque',
  'pretPage.learnMore': "l'assurance emprunteur",
  'pretPage.ctaTitle': "Prêt à économiser sur votre assurance emprunteur ?",
  'pretPage.ctaDesc': "Comparez gratuitement et changez d'assurance sans frais.",
  'pretPage.faq1.q': 'Ma banque peut-elle refuser ma nouvelle assurance ?',
  'pretPage.faq1.a': 'Non, si les garanties sont équivalentes. Elle doit accepter sous 10 jours ouvrés.',
  'pretPage.faq2.q': 'Quelles garanties sont obligatoires ?',
  'pretPage.faq2.a': 'Décès et PTIA sont toujours requis. ITT et IPT sont exigés pour les résidences principales.',
  'pretPage.faq3.q': 'Combien de temps prend le changement ?',
  'pretPage.faq3.a': "En moyenne 2 à 4 semaines entre la demande et l'entrée en vigueur du nouveau contrat.",
  'pretPage.faq4.q': 'Y a-t-il un questionnaire médical ?',
  'pretPage.faq4.a': 'Pas pour les prêts de moins de 200 000€ par personne sur 25 ans max (loi Lemoine).',

  // Prévoyance Page
  'prevoyancePage.title': 'Assurance Prévoyance',
  'prevoyancePage.subtitle': 'Protégez votre famille et préparez l\'avenir sereinement.',
  'prevoyancePage.adv1.title': 'Protection familiale',
  'prevoyancePage.adv1.desc': "Protégez vos proches en cas d'accident de la vie.",
  'prevoyancePage.adv2.title': 'Garanties sur mesure',
  'prevoyancePage.adv2.desc': 'Décès, invalidité, dépendance, obsèques.',
  'prevoyancePage.form.type': 'Type de prévoyance',
  'prevoyancePage.form.deces': 'Assurance décès',
  'prevoyancePage.form.obseques': 'Assurance obsèques',
  'prevoyancePage.form.dependance': 'Assurance dépendance',
  'prevoyancePage.form.incapacite': 'Garantie incapacité',
  'prevoyancePage.form.invalidite': 'Garantie invalidité',
  'prevoyancePage.form.situation': 'Situation familiale',
  'prevoyancePage.form.celibataire': 'Célibataire',
  'prevoyancePage.form.marie': 'Marié(e)',
  'prevoyancePage.form.pacse': 'Pacsé(e)',
  'prevoyancePage.form.divorce': 'Divorcé(e)',
  'prevoyancePage.form.veuf': 'Veuf/Veuve',
  'prevoyancePage.form.profession': 'Profession',
  'prevoyancePage.form.retraite': 'Retraité(e)',
  'prevoyancePage.form.risque': 'Profession à risque',
  'prevoyancePage.learnMore': 'la prévoyance',
  'prevoyancePage.ctaTitle': 'Prêt à protéger votre famille ?',
  'prevoyancePage.ctaDesc': 'Comparez gratuitement les meilleures offres de prévoyance.',
  'prevoyancePage.faq1.q': "Ai-je besoin de prévoyance si j'ai celle de mon entreprise ?",
  'prevoyancePage.faq1.a': "La prévoyance collective s'arrête en cas de départ. Un contrat individuel vous suit toute votre vie.",
  'prevoyancePage.faq2.q': 'À quel âge souscrire ?',
  'prevoyancePage.faq2.a': "Le plus tôt possible : les cotisations sont plus faibles et l'acceptation médicale plus facile.",
  'prevoyancePage.faq3.q': 'Quelle différence entre décès et obsèques ?',
  'prevoyancePage.faq3.a': "L'assurance décès verse un capital à vos proches. L'assurance obsèques finance spécifiquement vos funérailles.",

  // RC Pro Page
  'rcProPage.title': 'RC Professionnelle',
  'rcProPage.subtitle': 'Protégez votre activité contre les dommages causés à vos clients et tiers.',
  'rcProPage.adv1.title': 'Tarifs compétitifs',
  'rcProPage.adv1.desc': 'Comparez et économisez sur votre RC Pro.',
  'rcProPage.adv2.title': '15+ assureurs comparés',
  'rcProPage.adv2.desc': 'Les meilleures offres pro du marché.',
  'rcProPage.form.company': "Nom de l'entreprise",
  'rcProPage.form.companyPlaceholder': 'Votre entreprise',
  'rcProPage.form.sector': "Secteur d'activité",
  'rcProPage.form.commerce': 'Commerce',
  'rcProPage.form.services': 'Services',
  'rcProPage.form.batiment': 'Bâtiment',
  'rcProPage.form.conseil': 'Conseil',
  'rcProPage.form.sante': 'Santé',
  'rcProPage.form.artisanat': 'Artisanat',
  'rcProPage.form.informatique': 'Informatique',
  'rcProPage.form.autre': 'Autre',
  'rcProPage.form.employees': 'Nombre de salariés',
  'rcProPage.form.revenue': "Chiffre d'affaires annuel (€)",
  'rcProPage.form.claims': 'Sinistres sur 3 ans',
  'rcProPage.form.none': 'Aucun',
  'rcProPage.form.oneClaim': '1 sinistre',
  'rcProPage.form.twoClaims': '2 sinistres',
  'rcProPage.form.threePlus': '3 sinistres ou plus',
  'rcProPage.learnMore': 'la RC Pro',
  'rcProPage.ctaTitle': 'Prêt à protéger votre activité ?',
  'rcProPage.ctaDesc': 'Comparez gratuitement les meilleures offres RC Pro en 2 minutes.',
  'rcProPage.faq1.q': 'Quels dommages sont couverts ?',
  'rcProPage.faq1.a': "Dommages corporels, matériels et immatériels causés à des tiers dans le cadre de votre activité.",
  'rcProPage.faq2.q': 'La RC Pro couvre-t-elle mes salariés ?',
  'rcProPage.faq2.a': "Non, les salariés sont couverts par les accidents du travail. La RC Pro protège contre les dommages aux clients et tiers.",
  'rcProPage.faq3.q': 'Quel est le délai de mise en place ?',
  'rcProPage.faq3.a': 'Généralement immédiat ou sous 24-48h après la souscription.',

  // MRP Page
  'mrpPage.title': 'Multirisque Professionnelle',
  'mrpPage.subtitle': 'Protégez vos locaux, matériel et activité au meilleur prix.',
  'mrpPage.adv1.title': 'Tarifs compétitifs',
  'mrpPage.adv1.desc': 'Comparez et économisez sur votre MRP.',
  'mrpPage.adv2.title': 'Protection complète',
  'mrpPage.adv2.desc': 'Locaux, matériel, stocks couverts.',
  'mrpPage.form.local': 'Type de local',
  'mrpPage.form.propriete': 'Propriété',
  'mrpPage.form.location': 'Location',
  'mrpPage.form.bail': 'Bail commercial',
  'mrpPage.form.restauration': 'Restauration',
  'mrpPage.form.industrie': 'Industrie',
  'mrpPage.learnMore': 'la MRP',
  'mrpPage.ctaTitle': 'Prêt à protéger votre entreprise ?',
  'mrpPage.ctaDesc': 'Comparez gratuitement les meilleures offres MRP en 2 minutes.',
  'mrpPage.faq1.q': 'Que couvre exactement la MRP ?',
  'mrpPage.faq1.a': "Incendie, dégâts des eaux, vol, bris de machine, perte d'exploitation et responsabilité civile exploitation.",
  'mrpPage.faq2.q': "Comment évaluer le montant à assurer ?",
  'mrpPage.faq2.a': "Faites l'inventaire de vos locaux, matériel, stock et estimez la perte d'exploitation potentielle.",

  // GLI Page
  'gliPage.title': 'Garantie Loyer Impayé',
  'gliPage.subtitle': 'Protégez vos revenus locatifs et louez en toute sérénité.',
  'gliPage.adv1.title': 'Revenus sécurisés',
  'gliPage.adv1.desc': 'Protégez vos loyers contre les impayés.',
  'gliPage.adv2.title': 'Protection complète',
  'gliPage.adv2.desc': 'Loyers, dégradations, frais juridiques.',
  'gliPage.form.propertyType': 'Type de bien',
  'gliPage.form.apartment': 'Appartement',
  'gliPage.form.house': 'Maison',
  'gliPage.form.commercial': 'Local commercial',
  'gliPage.form.rent': 'Loyer mensuel (€)',
  'gliPage.form.tenantType': 'Type de locataire',
  'gliPage.form.individual': 'Particulier',
  'gliPage.form.company': 'Entreprise',
  'gliPage.form.student': 'Étudiant',
  'gliPage.learnMore': 'la GLI',
  'gliPage.ctaTitle': 'Prêt à sécuriser vos revenus locatifs ?',
  'gliPage.ctaDesc': 'Comparez gratuitement les meilleures offres GLI en 2 minutes.',
  'gliPage.faq1.q': "Quel est le coût moyen d'une GLI ?",
  'gliPage.faq1.a': 'Entre 2% et 4% du montant annuel des loyers charges comprises.',
  'gliPage.faq2.q': 'Quelles sont les garanties couvertes ?',
  'gliPage.faq2.a': 'Loyers impayés, dégradations locatives, protection juridique et frais de relogement.',
  'gliPage.faq3.q': 'La GLI est-elle cumulable avec un dépôt de garantie ?',
  'gliPage.faq3.a': "Non, la loi interdit de cumuler GLI et caution solidaire (sauf étudiant ou apprenti).",

  // PNO Page
  'pnoPage.title': 'Assurance PNO',
  'pnoPage.subtitle': "Protégez votre patrimoine immobilier même lorsque vous n'y habitez pas.",
  'pnoPage.adv1.title': 'Patrimoine protégé',
  'pnoPage.adv1.desc': 'Protégez votre bien même non occupé.',
  'pnoPage.adv2.title': 'Dès 9€/mois',
  'pnoPage.adv2.desc': 'Des tarifs très compétitifs.',
  'pnoPage.form.studio': 'Studio',
  'pnoPage.form.surface': 'Surface (m²)',
  'pnoPage.form.rooms': 'Nombre de pièces',
  'pnoPage.form.occupancy': "Statut d'occupation",
  'pnoPage.form.vacant': 'Bien vacant',
  'pnoPage.form.rental': 'Bien loué',
  'pnoPage.form.secondary': 'Résidence secondaire',
  'pnoPage.learnMore': "l'assurance PNO",
  'pnoPage.ctaTitle': 'Prêt à protéger votre patrimoine ?',
  'pnoPage.ctaDesc': 'Comparez gratuitement les meilleures offres PNO dès 9€/mois.',
  'pnoPage.faq1.q': 'Que couvre une assurance PNO ?',
  'pnoPage.faq1.a': "Dommages au bâtiment (incendie, dégâts des eaux, catastrophes naturelles), responsabilité civile et garanties optionnelles.",
  'pnoPage.faq2.q': "Quelle différence avec une assurance habitation ?",
  'pnoPage.faq2.a': "La PNO est conçue pour les biens non occupés par le propriétaire, généralement moins chère car elle ne couvre pas le contenu.",
  'pnoPage.faq3.q': "Mon locataire a sa propre assurance, ai-je quand même besoin de la PNO ?",
  'pnoPage.faq3.a': "Oui, l'assurance du locataire ne couvre pas les murs ni votre responsabilité de propriétaire.",

  // Gestion Locative Page
  'gestionPage.title': 'Gestion Locative en Ligne',
  'gestionPage.subtitle': 'Confiez vos biens à des professionnels et profitez de revenus sereins',
  'gestionPage.formTitle': 'Obtenez vos devis de gestion',
  'gestionPage.formDesc': 'Comparez les meilleures offres pour votre patrimoine',
  'gestionPage.form.propertyCount': 'Nombre de biens à gérer',
  'gestionPage.form.one': '1 bien',
  'gestionPage.form.twoFive': '2 à 5 biens',
  'gestionPage.form.fivePlus': 'Plus de 5 biens',
  'gestionPage.form.propertyType': 'Type de bien(s)',
  'gestionPage.form.apartments': 'Appartement(s)',
  'gestionPage.form.houses': 'Maison(s)',
  'gestionPage.form.mixed': 'Mixte',
  'gestionPage.form.totalRent': 'Loyers mensuels totaux (€)',
  'gestionPage.form.managementType': 'Type de gestion',
  'gestionPage.form.full': 'Gestion complète',
  'gestionPage.form.partial': 'Gestion partielle',
  'gestionPage.form.declaration': 'Gestion déclarative',
  'gestionPage.form.submit': 'Comparer les gestionnaires',
  'gestionPage.benefitsTitle': 'Avantages de la gestion locative',
  'gestionPage.benefit1': 'Gain de temps considérable',
  'gestionPage.benefit2': 'Expertise juridique et fiscale',
  'gestionPage.benefit3': 'Recherche et sélection des locataires',
  'gestionPage.benefit4': 'Gestion des impayés et contentieux',
  'gestionPage.benefit5': 'Suivi des travaux et entretien',
  'gestionPage.benefit6': 'Déclarations fiscales simplifiées',

  // Contact Page
  'contactPage.title': 'Contactez-nous',
  'contactPage.subtitle': 'Notre équipe est à votre écoute pour répondre à toutes vos questions',
  'contactPage.phone': 'Téléphone',
  'contactPage.phoneHours': 'Lun-Ven 9h-18h',
  'contactPage.email': 'Email',
  'contactPage.emailDelay': 'Réponse sous 24h',
  'contactPage.whatsapp': 'Écrivez-nous',
  'contactPage.whatsappDelay': 'Réponse instantanée',
  'contactPage.formTitle': 'Envoyez-nous un message',
  'contactPage.formDesc': 'Remplissez le formulaire ci-dessous et nous vous répondrons dans les plus brefs délais.',
  'contactPage.firstName': 'Prénom *',
  'contactPage.emailField': 'Email *',
  'contactPage.subject': 'Sujet *',
  'contactPage.message': 'Votre message (optionnel)',
  'contactPage.sending': 'Envoi en cours...',
  'contactPage.send': 'Envoyer le message',
  'contactPage.hours': "Horaires d'ouverture",
  'contactPage.weekdays': 'Lundi - Vendredi : 9h00 - 18h00',
  'contactPage.saturday': 'Samedi : 9h00 - 12h00',
  'contactPage.office': 'Notre siège',
  'contactPage.onlineService': 'Service 100% en ligne',
  'contactPage.quickQuote': "Besoin d'un devis rapide ?",
  'contactPage.quickQuoteDesc': 'Utilisez notre comparateur et recevez vos offres personnalisées en 2 minutes.',

  // Qui sommes-nous Page
  'aboutPage.title': 'Qui sommes-nous ?',
  'aboutPage.subtitle': "jemassuremoinscher.fr est votre partenaire de confiance pour trouver les meilleures offres d'assurance adaptées à vos besoins.",
  'aboutPage.users': 'Utilisateurs',
  'aboutPage.savings': "D'économies en moyenne",
  'aboutPage.experience': "Années d'expérience",
  'aboutPage.satisfaction': 'Satisfaction client',
  'aboutPage.missionTitle': 'Notre mission',
  'aboutPage.missionDesc': "Simplifier la comparaison des assurances et vous faire économiser sur vos contrats en toute transparence. Nous croyons que chacun mérite d'être bien assuré sans payer trop cher.",
  'aboutPage.expertiseTitle': 'Notre expertise',
  'aboutPage.expertiseDesc': "Plus de 10 ans d'expérience dans le domaine de l'assurance avec des experts dédiés à votre service, disponibles pour vous accompagner dans chaque étape.",
  'aboutPage.communityTitle': 'Notre communauté',
  'aboutPage.communityDesc': "Plus de 50 000 utilisateurs nous font confiance pour leurs comparaisons d'assurance. Rejoignez une communauté qui économise intelligemment.",
  'aboutPage.resultsTitle': 'Nos résultats',
  'aboutPage.resultsDesc': "En moyenne, nos utilisateurs économisent 35% sur leurs contrats d'assurance grâce à notre comparateur intelligent.",
  'aboutPage.valuesTitle': 'Nos valeurs',
  'aboutPage.transparency': 'Transparence',
  'aboutPage.transparencyDesc': 'Nous vous présentons toutes les offres sans parti pris',
  'aboutPage.independence': 'Indépendance',
  'aboutPage.independenceDesc': 'Notre service est gratuit et impartial',
  'aboutPage.simplicity': 'Simplicité',
  'aboutPage.simplicityDesc': 'Un processus de comparaison clair et rapide',
  'aboutPage.support': 'Accompagnement',
  'aboutPage.supportDesc': 'Notre équipe est là pour vous guider à chaque étape',
  'aboutPage.ctaTitle': 'Prêt à économiser sur vos assurances ?',
  'aboutPage.ctaDesc': "Comparez les meilleures offres en quelques clics et trouvez l'assurance qui vous correspond.",

  // Avis Clients Page
  'reviewsPage.title': 'Avis clients',
  'reviewsPage.subtitle': 'Découvrez ce que nos utilisateurs pensent de notre service',
  'reviewsPage.verifiedReviews': 'avis vérifiés',
  'reviewsPage.shareTitle': 'Vous aussi, partagez votre expérience !',
  'reviewsPage.shareDesc': 'Votre avis compte et nous aide à améliorer notre service pour mieux vous servir.',
  'reviewsPage.ctaTitle': 'Rejoignez nos clients satisfaits',
  'reviewsPage.ctaDesc': "Comparez les meilleures offres et économisez sur votre assurance dès aujourd'hui.",

  // Nos Partenaires Page
  'partnersPage.title': 'Nos partenaires assureurs',
  'partnersPage.subtitle': "Nous travaillons avec les plus grandes compagnies d'assurance françaises pour vous proposer les meilleures offres du marché.",
  'partnersPage.whyTitle': 'Pourquoi ces partenaires ?',
  'partnersPage.financial': 'Solidité financière',
  'partnersPage.financialDesc': 'Des assureurs reconnus et financièrement solides',
  'partnersPage.competitive': 'Tarifs compétitifs',
  'partnersPage.competitiveDesc': 'Les meilleurs prix négociés pour nos utilisateurs',
  'partnersPage.customerService': 'Service client',
  'partnersPage.customerServiceDesc': "Un accompagnement de qualité au quotidien",
  'partnersPage.national': 'Présence nationale',
  'partnersPage.nationalDesc': 'Des agences locales partout en France',
  'partnersPage.commitmentTitle': 'Notre engagement qualité',
  'partnersPage.commitmentDesc': "Nous sélectionnons nos partenaires selon des critères stricts. Chaque assureur présent dans notre comparateur a été soigneusement évalué pour vous garantir :",
  'partnersPage.commitment1': 'Une transparence totale sur les garanties et les tarifs',
  'partnersPage.commitment2': 'Un traitement rapide et efficace des sinistres',
  'partnersPage.commitment3': 'Un excellent rapport qualité-prix sur tous les contrats',
  'partnersPage.commitment4': 'Une relation de confiance durable avec nos utilisateurs',
  'partnersPage.ctaTitle': 'Comparez les offres de nos partenaires',
  'partnersPage.ctaDesc': "Trouvez l'assurance la moins chère en quelques clics grâce à notre comparateur.",

  // Blog Page
  'blogPage.title': 'Blog & Actualités Assurance',
  'blogPage.subtitle': "Conseils d'experts, guides pratiques et actualités légales pour tout savoir sur les assurances.",
  'blogPage.searchPlaceholder': 'Rechercher un article (ex: loi lemoine, assurance auto...)',
  'blogPage.noResults': 'Aucun article ne correspond à votre recherche',
  'blogPage.resetFilters': 'Réinitialiser les filtres',
  'blogPage.articlesFound': 'trouvé',
  'blogPage.articlesFoundPlural': 'trouvés',
  'blogPage.stayInformed': 'Restez informé',
  'blogPage.newsletterDesc': 'Abonnez-vous à notre newsletter pour recevoir nos derniers articles et conseils directement dans votre boîte mail.',
  'blogPage.guidesTitle': 'Guides Pratiques',
  'blogPage.legalTitle': 'Actualités Légales',
  'blogPage.expertTitle': 'Conseils Experts',
  'blogPage.byTypeTitle': 'Par Type',

  // Blog Article Page
  'blogArticlePage.backToBlog': 'Retour au blog',
  'blogArticlePage.share': 'Partager',
  'blogArticlePage.linkCopied': 'Lien copié !',
  'blogArticlePage.linkCopiedDesc': "Le lien de l'article a été copié dans le presse-papier.",
  'blogArticlePage.ctaTitle': 'Prêt à économiser sur vos assurances ?',
  'blogArticlePage.ctaDesc': "Comparez gratuitement les meilleures offres et trouvez l'assurance idéale en quelques clics",
  'blogArticlePage.compareBtn': 'Comparer les assurances',
  'blogArticlePage.relatedArticles': 'Articles similaires',

  // Plan du site
  'sitemapPage.title': 'Plan du site',
  'sitemapPage.subtitle': 'Retrouvez facilement toutes les pages de notre site pour comparer et trouver la meilleure assurance',
  'sitemapPage.insurances': 'Assurances',
  'sitemapPage.toolsServices': 'Outils & Services',
  'sitemapPage.blogResources': 'Blog & Ressources',
  'sitemapPage.legalInfo': 'Informations Légales',
  'sitemapPage.needHelp': "Besoin d'aide pour trouver votre assurance ?",
  'sitemapPage.helpDesc': "Notre équipe d'experts est là pour vous accompagner dans votre recherche",

  // Glossaire
  'glossairePage.title': "Glossaire de l'assurance",
  'glossairePage.subtitle': "Franchise, bonus-malus, tiers payant… Tous les termes d'assurance expliqués simplement avec des exemples concrets.",
  'glossairePage.searchPlaceholder': 'Rechercher un terme (ex: franchise, bonus-malus...)',
  'glossairePage.termsFound': 'terme',
  'glossairePage.termsFoundPlural': 'termes',
  'glossairePage.noResults': 'Aucun terme ne correspond à votre recherche',
  'glossairePage.ctaTitle': "Besoin d'aide pour choisir votre assurance ?",
  'glossairePage.ctaDesc': "Comparez gratuitement les meilleures offres et économisez sur vos contrats d'assurance.",
  'glossairePage.compareBtn': 'Comparer les assurances',

  // Glossaire Terme
  'glossaireTermPage.notFound': 'Terme non trouvé',
  'glossaireTermPage.notFoundDesc': "Ce terme n'existe pas dans notre glossaire.",
  'glossaireTermPage.backToGlossary': 'Retour au glossaire',
  'glossaireTermPage.relatedTerms': 'Termes associés',
  'glossaireTermPage.ctaTitle': 'Comparez et économisez sur votre assurance',
  'glossaireTermPage.ctaDesc': "Trouvez la meilleure offre en quelques clics. Gratuit et sans engagement.",

  // Callback Form
  'callbackForm.title': "Besoin d'être",
  'callbackForm.titleHighlight': 'rappelé ?',
  'callbackForm.subtitle': 'Un conseiller vous contactera gratuitement au moment qui vous convient',
  'callbackForm.fullName': 'Nom complet *',
  'callbackForm.email': 'Email *',
  'callbackForm.phone': 'Téléphone *',
  'callbackForm.timeSlot': 'Créneau préféré *',
  'callbackForm.timeSlotPlaceholder': 'Choisir un créneau',
  'callbackForm.morning': 'Matin (9h-12h)',
  'callbackForm.afternoon': 'Après-midi (14h-17h)',
  'callbackForm.evening': 'Soir (17h-19h)',
  'callbackForm.message': 'Message (optionnel)',
  'callbackForm.messagePlaceholder': 'Précisez votre demande...',
  'callbackForm.submit': 'Demander un rappel gratuit',
  'callbackForm.sending': 'Envoi en cours...',
  'callbackForm.required': '* Champs obligatoires. Rappel gratuit sous 24h ouvrées.',
  'callbackForm.successTitle': 'Demande de rappel enregistrée !',
  'callbackForm.successDesc': 'Merci pour votre confiance. Un de nos conseillers vous contactera dans les meilleurs délais au créneau que vous avez choisi.',
  'callbackForm.newRequest': 'Faire une nouvelle demande',

  // Quick Help Section
  'quickHelp.title': "Besoin d'aide ?",
  'quickHelp.bubble': 'Une question ? Je vous réponds en moins de 2 min !',
  'quickHelp.firstName': 'Prénom',
  'quickHelp.email': 'Email',
  'quickHelp.subject': 'Sujet',
  'quickHelp.send': 'Envoyer',
  'quickHelp.sending': 'Envoi en cours...',

  // Simplified Lead Form
  'leadForm.callbackGuarantee': 'Rappel garanti sous 2h',
  'leadForm.getQuote': 'Obtenez votre devis',
  'leadForm.formSpeed': 'Formulaire en 30 secondes • 100% gratuit',
  'leadForm.fullName': 'Nom complet *',
  'leadForm.email': 'Email *',
  'leadForm.phone': 'Téléphone *',
  'leadForm.submit': '🎯 Obtenir mon devis gratuit',
  'leadForm.sending': 'Envoi en cours...',
  'leadForm.disclaimer': '✅ Sans engagement • 🔒 Données sécurisées • ⚡ Réponse sous 2h',
  'leadForm.successTitle': '🎉 Demande envoyée !',
  'leadForm.successDesc': 'Un de nos experts vous contacte dans les',
  'leadForm.successTime': '2 heures',
  'leadForm.successEnd': 'pour vous proposer les meilleures offres.',
  'leadForm.meanwhile': 'Pendant ce temps :',
  'leadForm.comparing': 'Comparaison de',
  'leadForm.insurers': '30+ assureurs',
  'leadForm.preparing': 'Préparation de votre',
  'leadForm.personalQuote': 'devis personnalisé',
  'leadForm.checkPhoneEmail': 'Vérifiez votre',
  'leadForm.phoneAndEmail': 'téléphone et email',

  // Insurance Quiz
  'quiz.title': 'Trouvez votre assurance idéale en 3 questions',
  'quiz.subtitle': 'Répondez à notre quiz et recevez des recommandations personnalisées',
  'quiz.question': 'Question',
  'quiz.of': 'sur',
  'quiz.resultTitle': 'Votre assurance idéale vous attend !',
  'quiz.resultDesc': 'Recevez vos recommandations personnalisées par email',
  'quiz.fullName': 'Nom complet',
  'quiz.email': 'Email',
  'quiz.seeResults': 'Voir mes recommandations',
  'quiz.sending': 'Envoi en cours...',
  'quiz.recommendations': 'Vos recommandations personnalisées',
  'quiz.savingsPerYear': "d'économies/an",
  'quiz.compareOffers': 'Comparer les offres',
  'quiz.restart': 'Recommencer le quiz',
  'quiz.q1': 'Quel est votre besoin principal ?',
  'quiz.q1.vehicle': '🚗 Assurer mon véhicule',
  'quiz.q1.health': '🏥 Protéger ma santé',
  'quiz.q1.home': '🏠 Sécuriser mon logement',
  'quiz.q1.family': '👨‍👩‍👧 Protéger ma famille',
  'quiz.q2': 'Quelle est votre situation actuelle ?',
  'quiz.q2.new': "🆕 Je n'ai pas encore d'assurance",
  'quiz.q2.expensive': '😕 Mon assurance actuelle est trop chère',
  'quiz.q2.change': "🔄 J'ai un changement de situation",
  'quiz.q2.compare': '🔍 Je veux simplement comparer',
  'quiz.q3': 'Quel est votre objectif principal ?',
  'quiz.q3.save': '💰 Économiser sur mes cotisations',
  'quiz.q3.coverage': '🛡️ Obtenir une meilleure couverture',
  'quiz.q3.callback': '⚡ Être rappelé rapidement',
  'quiz.q3.advice': '💬 Être accompagné par un expert',

  // AI Chatbot
  'chatbot.greeting': "Bonjour ! Je suis votre assistant assurance. Comment puis-je vous aider aujourd'hui ?",
  'chatbot.title': 'Assistant Assurance IA',
  'chatbot.online': 'En ligne • Réponse instantanée',
  'chatbot.openLabel': "Ouvrir l'assistant virtuel",
  'chatbot.closeLabel': "Fermer l'assistant",
  'chatbot.placeholder': 'Posez votre question...',
  'chatbot.sendLabel': 'Envoyer le message',
  'chatbot.talkToHuman': 'Parler à un conseiller humain',
  'chatbot.footer': 'Assistant IA • Réponses instantanées 24/7',
  'chatbot.advisorsAvailable': '• Conseillers disponibles',
  'chatbot.errorTitle': 'Erreur',
  'chatbot.errorDesc': "Impossible de contacter l'assistant. Veuillez réessayer.",
  'chatbot.errorMessage': 'Désolé, je rencontre un problème technique. Pouvez-vous reformuler votre question ?',

  // Transfer Dialog
  'transfer.title': 'Parler à un conseiller',
  'transfer.desc': 'Un conseiller humain prendra contact avec vous dans les plus brefs délais. Horaires : Lundi-Vendredi, 9h-18h',
  'transfer.fullName': 'Nom complet *',
  'transfer.email': 'Email *',
  'transfer.phone': 'Téléphone',
  'transfer.reason': 'Motif de la demande (optionnel)',
  'transfer.reasonPlaceholder': 'Décrivez brièvement votre besoin...',
  'transfer.cancel': 'Annuler',
  'transfer.submit': 'Demander un transfert',
  'transfer.sending': 'Envoi...',
  'transfer.successTitle': 'Demande envoyée !',
  'transfer.successDesc': 'Un conseiller va vous contacter sous peu.',

  // Newsletter Section
  'newsletter.title': 'Restez informé des',
  'newsletter.titleHighlight': 'meilleures offres',
  'newsletter.desc': "Recevez nos conseils d'experts, comparatifs exclusifs et les dernières promotions directement dans votre boîte mail.",
  'newsletter.freeNoSpam': '100% gratuit, 0% spam.',
  'newsletter.subscribing': 'Inscription...',
  'newsletter.subscribe': "S'inscrire gratuitement",
  'newsletter.checkEmail': '📧 Vérifiez votre email !',
  'newsletter.confirmationSent': "Un email de confirmation vous a été envoyé. Cliquez sur le lien pour confirmer votre abonnement et commencer à recevoir nos offres exclusives.",
  'newsletter.otherEmail': "S'inscrire avec un autre email",
  'newsletter.noCommitment': '✓ Sans engagement',
  'newsletter.oneClickUnsub': '✓ Désinscription en 1 clic',
  'newsletter.secureData': '✓ Données sécurisées',

  // Blog Highlights
  'blogHighlights.badge': 'Blog & Actualités',
  'blogHighlights.title': 'Guides et Conseils Assurance 2025',
  'blogHighlights.subtitle': "Découvrez nos articles experts pour bien choisir votre assurance et économiser jusqu'à 947€ par an",
  'blogHighlights.readArticle': "Lire l'article",
  'blogHighlights.viewAll': 'Voir tous les articles',

  // Comments Section
  'comments.title': 'Commentaires',
  'comments.leaveComment': 'Laisser un commentaire',
  'comments.name': 'Nom *',
  'comments.namePlaceholder': 'Votre nom',
  'comments.email': 'Email * (non publié)',
  'comments.emailPlaceholder': 'votre@email.com',
  'comments.comment': 'Commentaire *',
  'comments.commentPlaceholder': 'Partagez votre expérience ou posez une question...',
  'comments.sending': 'Envoi en cours...',
  'comments.submit': 'Publier le commentaire',
  'comments.moderation': "Votre commentaire sera publié après modération. Les champs marqués d'un * sont obligatoires.",
  'comments.loading': 'Chargement des commentaires...',
  'comments.noComments': 'Aucun commentaire pour le moment. Soyez le premier à commenter !',
  'comments.successTitle': 'Commentaire envoyé !',
  'comments.successDesc': 'Votre commentaire sera publié après modération.',

  // FAQ Component
  'faqComponent.badge': 'FAQ',
  'faqComponent.title': 'Questions',
  'faqComponent.titleHighlight': 'fréquentes',
  'faqComponent.subtitle': "Trouvez rapidement les réponses à vos questions sur notre comparateur d'assurances",

  // Features Component
  'featuresComponent.badge': 'Nos engagements',
  'featuresComponent.title': 'Pourquoi choisir',
  'featuresComponent.feature1.title': '120 assureurs',
  'featuresComponent.feature1.desc': 'Le panel le plus large du web',
  'featuresComponent.feature2.title': '+ 10 millions d\'internautes',
  'featuresComponent.feature2.desc': 'Accompagnés',
  'featuresComponent.feature3.title': 'Comparaison des garanties',
  'featuresComponent.feature3.desc': 'ET du rapport qualité-prix',
  'featuresComponent.feature4.title': 'Service gratuit',
  'featuresComponent.feature4.desc': 'Et sans engagement',

  // Partners Component
  'partnersComponent.badge': 'Nos partenaires',
  'partnersComponent.title': 'Plus de',
  'partnersComponent.titleHighlight': '120 assureurs',
  'partnersComponent.titleEnd': 'comparés',
  'partnersComponent.subtitle': 'Et près de',
  'partnersComponent.agencies': '8000 agences locales',
  'partnersComponent.autoScroll': 'Le carrousel défile automatiquement. Passez la souris dessus pour mettre en pause.',

  // Landing Pages Common
  'landing.urgency': 'Plus que 12 places aujourd\'hui',
  'landing.no1': 'N°1',
  'landing.inFrance': 'en France',
  'landing.upTo': "jusqu'à",
  'landing.compare': 'Comparez',
  'landing.perYear': '/an',
  'landing.savingsAvg': 'Économie moy.',
  'landing.forQuote': 'Pour le devis',
  'landing.whyChooseUs': 'Pourquoi nous choisir pour votre',
  'landing.freeNoCommitment': '100% gratuit et sans engagement',
  'landing.expertCallback': 'Expert dédié qui vous rappelle sous 2h',
  'landing.savingsGuaranteed': 'Économies garanties ou remboursé',
  'landing.customerReviews': 'Avis clients',
  'landing.sslSecure': 'SSL Sécurisé',
  'landing.servicePremium': 'Service Premium',
};

// English translations
const en: Record<string, string> = {
  // Header
  'nav.individuals': 'Individuals',
  'nav.professionals': 'Business',
  'nav.lifeAndSavings': 'Life & Savings',
  'nav.realEstate': 'Real Estate',
  'nav.aboutUs': 'About Us',
  'nav.partners': 'Our Partners',
  'nav.reviews': 'Customer Reviews',
  'nav.blog': 'Blog',
  'nav.openMenu': 'Open menu',
  'nav.closeMenu': 'Close menu',
  'nav.back': 'Back',
  'nav.share': 'Share',
  'nav.favorites': 'Favorites',
  'nav.print': 'Print',
  'nav.moreActions': 'More actions',
  
  // Insurance types
  'insurance.auto': 'Auto',
  'insurance.moto': 'Motorcycle',
  'insurance.home': 'Home',
  'insurance.health': 'Health',
  'insurance.pets': 'Pets',
  'insurance.rcPro': 'Professional Liability',
  'insurance.mrp': 'Business Property',
  'insurance.life': 'Life Insurance',
  'insurance.loan': 'Loan Insurance',
  'insurance.provident': 'Income Protection',
  'insurance.gli': 'Rent Guarantee',
  'insurance.pno': 'Landlord Insurance',
  'insurance.rentalManagement': 'Property Management',
  
  // Hero
  'hero.title': 'The site to find cheaper insurance,',
  'hero.titleHighlight': 'without compromise.',
  'hero.subtitle': 'Compare',
  'hero.subtitleBold': '50+ insurers',
  'hero.subtitleEnd': 'in 2 minutes.',
  'hero.subtitleSecondary': 'Free and no commitment.',
  'hero.savingsBadge': 'Save up to',
  'hero.savingsPercent': '40%',
  'hero.savingsEnd': 'on your current insurance',
  'hero.arthurSpeech': "I'm Arthur!",
  'hero.partnersCount': 'Partner insurers',
  'hero.compareTime': 'Express comparison',
  'hero.freeLabel': 'Free & no commitment',
  
  // Categories
  'category.auto': 'Auto',
  'category.moto': 'Moto',
  'category.home': 'Home',
  'category.health': 'Health',
  'category.pets': 'Pets',
  'category.life': 'Life',
  
  // Features
  'features.title': 'Why Choose Us?',
  'features.subtitle': 'Exclusive benefits to support you',
  'features.free.title': '100% Free',
  'features.free.description': 'Our comparison service is completely free with no obligation.',
  'features.fast.title': 'Fast & Simple',
  'features.fast.description': 'Get your quotes in less than 2 minutes.',
  'features.expert.title': 'Dedicated Experts',
  'features.expert.description': 'A team of advisors available to assist you.',
  'features.secure.title': 'Secure Data',
  'features.secure.description': 'Your information is protected and confidential.',
  
  // FAQ
  'faq.title': 'Frequently Asked Questions',
  'faq.subtitle': 'Everything you need to know about our comparator',
  
  // Footer
  'footer.tagline': 'Arthur, your insurance savings superhero.',
  'footer.insurances': 'Our Insurance',
  'footer.about': 'About',
  'footer.info': 'Information',
  'footer.cookies': 'Cookies',
  'footer.legal': 'Legal Notice',
  'footer.terms': 'Terms of Use',
  'footer.privacy': 'Privacy',
  'footer.contact': 'Contact',
  'footer.sitemap': 'Sitemap',
  'footer.newsletter': 'Newsletter',
  'footer.rights': 'All rights reserved',
  'footer.privacyCharter': 'Privacy Policy',
  'footer.securePayment': 'Secure Payment',
  'footer.gdprProtected': 'GDPR Protected Data',
  'footer.verifiedSite': 'Verified Site',
  'footer.disclaimer': 'Jemassuremoinscher.fr is an independent comparison site. Displayed rates are indicative and may vary based on your profile. This site does not replace advice from an insurance professional.',
  'footer.description': 'Compare the best insurance in France. Free, fast and no commitment.',
  'footer.legalSection': 'Legal',
  'footer.privacyPolicy': 'Privacy Policy',
  'footer.cookiePolicy': 'Cookie Policy',
  
  // Testimonials
  'testimonials.title': 'They Trust Us',
  'testimonials.subtitle': 'Discover reviews from our satisfied customers who saved on their insurance',
  'testimonials.avgRating': 'Average rating',
  'testimonials.satisfiedClients': 'Satisfied customers',
  'testimonials.satisfactionRate': 'Satisfaction rate',
  'testimonials.avgSavings': 'Average savings',
  'testimonials.t1.text': "I saved €450 on my car insurance in just a few clicks! The service is fast and the offers are really competitive. Highly recommended.",
  'testimonials.t1.insurance': 'Car Insurance',
  'testimonials.t2.text': "Excellent comparison tool! I found home insurance 30% cheaper than my previous one. The process is simple and no commitment.",
  'testimonials.t2.insurance': 'Home Insurance',
  'testimonials.t3.text': "Very satisfied! In 2 minutes I compared several health plans and found the one that perfectly matches my needs. A real time saver.",
  'testimonials.t3.insurance': 'Health Insurance',
  'testimonials.t4.text': "Efficient and free service. I was able to easily compare all motorcycle insurance on the market. Advisors are available if needed.",
  'testimonials.t4.insurance': 'Motorcycle Insurance',
  'testimonials.t5.text': "I didn't think I could save so much on my loan insurance! The comparison tool saved me over €800 per year. Thank you!",
  'testimonials.t5.insurance': 'Loan Insurance',
  'testimonials.t6.text': "Perfect for finding the best insurance for my dog. The prices are transparent and I received my quote instantly.",
  'testimonials.t6.insurance': 'Pet Insurance',
  
  // Partners
  'partners.title': 'Our Partners',
  'partners.subtitle': 'Over 120 trusted insurers',
  
  // Common
  'common.learnMore': 'Learn more',
  'common.getQuote': 'Get a quote',
  'common.compare': 'Compare',
  'common.free': 'Free',
  'common.close': 'Close',
  'common.loading': 'Loading...',
  'common.back': 'Back',
  'common.continue': 'Continue',
  'common.send': 'Send',
  'common.readMore': 'Read more',
  'common.advice': 'Tip',
  'common.cancel': 'Cancel',
  'common.confirm': 'Confirm',
  'common.sending': 'Sending...',
  'common.perMonth': 'per month',
  'common.perYear': 'per year',
  
  // How it works
  'howItWorks.title': 'How It Works',
  'howItWorks.subtitle': 'Comparing insurance has never been easier',
  'howItWorks.step1.title': 'Fill in my profile',
  'howItWorks.step1.description': 'In 2 minutes, describe your insurance needs.',
  'howItWorks.step2.title': 'Compare offers',
  'howItWorks.step2.description': 'Arthur analyses 50+ insurers for you.',
  'howItWorks.step3.title': 'Get a callback right away',
  'howItWorks.step3.description': 'Choose the best offer and get called back.',
  'howItWorks.arthurCta': 'takes care of everything!',
  
  // Why us
  'whyUs.title': 'Why Choose Us?',
  'whyUs.subtitle': 'Discover what sets us apart from other comparison sites',
  'whyUs.criteria': 'Criteria',
  'whyUs.others': 'Other comparison sites',
  'whyUs.othersMobile': 'Others',
  'whyUs.speed': 'Speed',
  'whyUs.speedUs': 'Quote in 2 minutes',
  'whyUs.speedThem': 'Up to 15 minutes',
  'whyUs.insurerCount': 'Number of insurers',
  'whyUs.insurerCountUs': '50+ partners',
  'whyUs.insurerCountThem': '10-20 insurers',
  'whyUs.transparency': 'Price transparency',
  'whyUs.transparencyUs': 'No surprise pricing',
  'whyUs.transparencyThem': 'Frequent hidden fees',
  'whyUs.mascot': 'Favourite mascot',
  'whyUs.mascotUs': 'Arthur, the superhero!',
  'whyUs.mascotThem': 'No mascot 😢',
  'whyUs.didYouKnow': 'Did you know that',
  'whyUs.9outOf10': '9 out of 10 customers',
  'whyUs.save': 'save',
  'whyUs.perYear': 'per year',
  'whyUs.googleReviews': 'on Google Reviews • 250+ reviews',
  'whyUs.service100': '100% Service',
  'whyUs.freeService': 'Free',
  'whyUs.data': 'Data',
  'whyUs.secured': 'Secured',
  'whyUs.arthurSays': 'Arthur says:',
  'whyUs.arthurQuote': '"I negotiate the',
  'whyUs.bestRates': 'best rates',
  
  // SEO FAQ
  'seoFaq.title': 'Frequently Asked Questions',
  'seoFaq.subtitle': 'Everything you need to know about insurance comparison',
  'seoFaq.q1': 'How can I save on my car insurance?',
  'seoFaq.a1': 'To save on your car insurance, compare offers from multiple insurers with our free comparison tool. Analyse the coverage offered, adjust your deductible, and take advantage of safe driver discounts. On average, our users save €320 per year on their car insurance.',
  'seoFaq.q2': 'Is it really free?',
  'seoFaq.a2': 'Yes, our comparison service is 100% free with no commitment. We are only compensated by partner insurers if you take out a policy. You never pay any additional fees to use our comparison tool.',
  'seoFaq.q3': 'Can I switch insurance at any time?',
  'seoFaq.a3': "Since the Hamon law of 2015, you can cancel your car, motorcycle or home insurance contract at any time after the first year. For health insurance, cancellation is possible on the contract anniversary date with 2 months' notice, or at any time after the first year thanks to infra-annual cancellation.",
  'seoFaq.moreQuestions': 'More questions?',
  'seoFaq.arthurHere': 'is here for you!',
  
  // Quick Quote
  'quickQuote.srTitle': 'Auto and health insurance simulator',
  'quickQuote.title': 'My Quick Quote',
  'quickQuote.subtitle': 'Arthur calculates your savings in 30 seconds',
  'quickQuote.vehicleQuestion': 'What is your vehicle?',
  'quickQuote.ageQuestion': 'How old are you?',
  'quickQuote.contactQuestion': 'Your contact details for the quote',
  'quickQuote.emailLabel': 'Your email',
  'quickQuote.phoneLabel': 'Your phone',
  'quickQuote.privacyNote': 'An expert will call you back to offer the best rate. Your data is protected and will never be shared.',
  'quickQuote.submit': 'Get my quote',
  'quickQuote.sending': 'Sending...',
  'quickQuote.successTitle': 'Request sent!',
  'quickQuote.successText': 'An expert will call you back within',
  'quickQuote.successTime': '2 hours',
  'quickQuote.successEnd': 'to offer you the best rate.',
  'quickQuote.successCheck': 'Check your phone and email.',
  'quickQuote.secureData': '🔒 Your data is secure and confidential',
  'quickQuote.citadine': 'City car',
  'quickQuote.citadineDesc': 'Small city car',
  'quickQuote.berline': 'Sedan',
  'quickQuote.berlineDesc': 'Comfort and space',
  'quickQuote.suv': 'SUV / 4x4',
  'quickQuote.suvDesc': 'Off-road',
  'quickQuote.toastSuccess': 'Request sent! We will contact you very soon.',
  'quickQuote.toastError': 'Error. Please try again.',
  
  // Guides
  'guides.mainTitle': 'Everything you need to pay less',
  'guides.mainSubtitle': 'Arthur shares his best tips to optimise your insurance contracts',
  'guides.arthurSpeech': 'Must read! 📚',
  'guides.cta': 'Start my free comparison',
  'guides.article1.title': 'Hamon Law: how to cancel?',
  'guides.article1.excerpt': 'Cancel your insurance at any time after 1 year of contract.',
  'guides.article2.title': '5 tips to reduce your premium',
  'guides.article2.excerpt': "Discover our expert advice to save up to 40%.",
  'guides.article3.title': 'New driver: what budget?',
  'guides.article3.excerpt': 'Complete guide to insuring your first car at the best price.',
  
  // Sticky CTA
  'stickyCta.text': 'Start my free comparison',
  
  // Insurance labels for footer
  'footer.autoInsurance': 'Car Insurance',
  'footer.motoInsurance': 'Motorcycle Insurance',
  'footer.homeInsurance': 'Home Insurance',
  'footer.healthInsurance': 'Health Insurance',
  'footer.petInsurance': 'Pet Insurance',
  'footer.lifeInsurance': 'Life Insurance',
  'footer.whoAreWe': 'About Us',
  'footer.ourPartners': 'Our Partners',
  
  // Pages
  'page.blog.title': 'Blog',
  'page.blog.subtitle': 'Insurance tips and news',
  'page.about.title': 'About Us',
  'page.about.subtitle': 'Discover our history and mission',
  'page.partners.title': 'Our Partners',
  'page.partners.subtitle': 'Discover our partner insurers',
  'page.contact.title': 'Contact Us',
  'page.contact.subtitle': 'Our team is here to help',

  // Savings Calculator
  'calc.title': 'Calculate your',
  'calc.titleHighlight': 'potential savings',
  'calc.subtitle': 'Discover how much you could save by switching insurance',
  'calc.yourInfo': 'Your information',
  'calc.insuranceType': 'Insurance type',
  'calc.autoIns': 'Car Insurance',
  'calc.motoIns': 'Motorcycle Insurance',
  'calc.homeIns': 'Home Insurance',
  'calc.healthIns': 'Health Insurance',
  'calc.currentPrice': 'Current monthly price (€)',
  'calc.yourAge': 'Your age',
  'calc.vehicleAge': 'Vehicle age (years)',
  'calc.calculate': 'Calculate my savings',
  'calc.potentialSavings': 'Your potential savings',
  'calc.fillForm': 'Fill in the form to see your potential savings',
  'calc.currentPriceLabel': 'Current price',
  'calc.estimatedPrice': 'Estimated price',
  'calc.savings': 'savings',
  'calc.monthlySaving': 'Monthly saving',
  'calc.annualSaving': 'Annual saving',
  'calc.vacationMsg': 'years, you will have saved enough for a holiday! 🏖️',
  'calc.compareNow': 'Compare offers now',
  'calc.disclaimer': '* Estimate based on average savings observed. Actual savings may vary depending on your profile.',

  // Quote Request Form
  'quoteForm.title': 'Request your',
  'quoteForm.titleHighlight': 'free quote',
  'quoteForm.subtitle': 'Fill in this form and receive your personalised quote within 24h',
  'quoteForm.insuranceType': 'Insurance type *',
  'quoteForm.selectType': 'Select a type',
  'quoteForm.autoIns': 'Car Insurance',
  'quoteForm.motoIns': 'Motorcycle Insurance',
  'quoteForm.homeIns': 'Home Insurance',
  'quoteForm.healthIns': 'Health Insurance',
  'quoteForm.loanIns': 'Loan Insurance',
  'quoteForm.petIns': 'Pet Insurance',
  'quoteForm.fullName': 'Full name *',
  'quoteForm.email': 'Email *',
  'quoteForm.phone': 'Phone *',
  'quoteForm.postalCode': 'Postal code *',
  'quoteForm.currentInsurer': 'Current insurer (optional)',
  'quoteForm.acceptTerms': 'I accept the terms and conditions and privacy policy *',
  'quoteForm.submit': 'Get my free quote',
  'quoteForm.submitting': 'Sending...',
  'quoteForm.required': '* Required fields. Your data is secure and will never be shared.',
  'quoteForm.successTitle': 'Request sent successfully!',
  'quoteForm.successText': 'Your quote request has been registered. One of our advisors will contact you within 24 hours to offer you the best deals suited to your profile.',
  'quoteForm.newRequest': 'Make a new request',
  'quoteForm.toastSuccess': 'Request sent!',
  'quoteForm.toastSuccessDesc': 'We will contact you within 24h with your personalised quote.',
  'quoteForm.toastError': 'Error',
  'quoteForm.toastErrorDesc': 'An error occurred. Please try again.',

  // Insurance Comparison
  'comparison.title': 'Offer Comparison',
  'comparison.subtitle': 'Here are the 10 best offers for your profile',
  'comparison.bestOffer': 'Best offer',
  'comparison.callbackBtn': 'Get a callback',
  'comparison.newRequest': 'Make a new request',

  // Insurance FAQ
  'insuranceFaq.defaultTitle': 'Frequently Asked Questions',

  // Cookie Banner
  'cookies.title': 'Cookie Management',
  'cookies.description': 'We use cookies to improve your experience',
  'cookies.text': 'We use cookies to personalise content and ads, to provide social media features and to analyse our traffic. You can accept all cookies or manage your preferences.',
  'cookies.learnMore': 'Learn more',
  'cookies.acceptAll': 'Accept all',
  'cookies.rejectAll': 'Reject all',
  'cookies.customize': 'Customise',
  'cookies.necessary': 'Necessary cookies',
  'cookies.necessaryDesc': 'Essential for the website to function. Always enabled.',
  'cookies.analytics': 'Analytics cookies',
  'cookies.analyticsDesc': 'Help us understand how you use our site.',
  'cookies.marketing': 'Marketing cookies',
  'cookies.marketingDesc': 'Used to display relevant advertisements.',
  'cookies.savePreferences': 'Save my preferences',

  // Interactive Comparator
  'comparator.badge': 'Real-Time Comparator',
  'comparator.heroTitle': 'Discover your potential savings',
  'comparator.heroSubtitle': 'Instantly compare the best offers on the market',
  'comparator.insuranceType': 'Insurance type',
  'comparator.autoIns': '🚗 Car Insurance',
  'comparator.motoIns': '🏍️ Motorcycle Insurance',
  'comparator.homeIns': '🏠 Home Insurance',
  'comparator.healthIns': '💊 Health Insurance',
  'comparator.sortBy': 'Sort by',
  'comparator.bestSavings': '💰 Best savings',
  'comparator.lowestPrice': '💵 Lowest price',
  'comparator.bestRating': '⭐ Best rating',
  'comparator.currentPrice': 'Your current price',
  'comparator.yearlySavings': 'Potential savings over 1 year',
  'comparator.switchingTo': 'By switching to our best offer at',
  'comparator.offersAvailable': 'offers available',
  'comparator.share': 'Share',
  'comparator.bestOfferBadge': 'Best offer',
  'comparator.popular': '⭐ Popular',
  'comparator.callbackBtn': 'Get a callback',
  'comparator.needHelp': 'Need help choosing?',
  'comparator.expertHelp': 'Our experts compare all offers for free and advise you on the best solution',
  'comparator.talkExpert': 'Talk to an expert for free',
  'comparator.linkCopied': 'Link copied!',

  // Subscription Modal
  'subModal.title': 'Callback request',
  'subModal.fullName': 'Full name *',
  'subModal.email': 'Email *',
  'subModal.phone': 'Phone *',
  'subModal.acceptTerms': 'I accept the terms and conditions and privacy policy *',
  'subModal.successTitle': 'Request sent!',
  'subModal.successText': 'We will contact you within 24h to assist you.',
  'subModal.toastSuccess': 'Request sent successfully!',
  'subModal.toastError': 'An error occurred. Please try again.',

  // Trust Badges
  'trust.secureData': 'Secure Data',
  'trust.secureDataDesc': 'GDPR compliant',
  'trust.certified': 'Quality Certified',
  'trust.certifiedDesc': 'Verified service',
  'trust.securePay': 'Secure Payments',
  'trust.securePayDesc': 'SSL/TLS',
  'trust.clients': '50,000+ clients',
  'trust.clientsDesc': 'Trust us',
  'trust.savingsGuaranteed': 'Savings Guaranteed',
  'trust.savingsGuaranteedDesc': 'Or refunded',
  'trust.noCommitment': 'No Commitment',
  'trust.noCommitmentDesc': '100% free',

  // NotFound
  'notFound.title': '404',
  'notFound.text': 'Oops! Page not found',
  'notFound.link': 'Return to Home',

  // Insurance Pages Common
  'insPage.compareNow': 'Compare now',
  'insPage.getQuote': 'Get your personalised quote',
  'insPage.loading': 'Sending...',
  'insPage.compareOffers': 'Compare offers',
  'insPage.learnMore': 'Learn more about',
  'insPage.faqTitle': 'Frequently Asked Questions',
  'insPage.readyToSave': 'Ready to save on your',
  'insPage.compareFree': 'Compare the best offers for free in 2 minutes.',
  'insPage.compareNowBtn': 'Compare offers now',
  'insPage.quoteIn2min': 'Quote in 2 minutes',
  'insPage.quoteIn2minDesc': 'Simple, fast and 100% free.',
  'insPage.select': 'Select',
  'insPage.postalCode': 'Postal code',
  'insPage.yourAge': 'Your age',

  // Auto Page
  'autoPage.title': 'Car Insurance',
  'autoPage.subtitle': 'Compare the best offers and save up to €400 per year.',
  'autoPage.adv1.title': 'Save up to €400',
  'autoPage.adv1.desc': 'Compare and save on your car insurance.',
  'autoPage.adv2.desc': 'The best offers on the market.',
  'autoPage.adv2.title': '20+ insurers compared',
  'autoPage.form.brand': 'Vehicle brand',
  'autoPage.form.brandPlaceholder': 'Select a brand',
  'autoPage.form.model': 'Model',
  'autoPage.form.modelPlaceholder': 'Enter the model',
  'autoPage.form.modelFirst': 'Select a brand first',
  'autoPage.form.modelSelect': 'Select a model',
  'autoPage.form.year': 'Year',
  'autoPage.form.fuel': 'Fuel',
  'autoPage.form.fuel.essence': 'Petrol',
  'autoPage.form.fuel.diesel': 'Diesel',
  'autoPage.form.fuel.electric': 'Electric',
  'autoPage.form.fuel.hybrid': 'Hybrid',
  'autoPage.form.license': 'Date licence obtained',
  'autoPage.form.bonusMalus': 'No-claims bonus coefficient',
  'autoPage.form.bonusMalusPlaceholder': 'Select your coefficient',
  'autoPage.form.bonus050': '0.50 (Maximum bonus)',
  'autoPage.form.bonus060': '0.60 (9 years no claims)',
  'autoPage.form.bonus070': '0.70 (6 years no claims)',
  'autoPage.form.bonus080': '0.80 (3 years no claims)',
  'autoPage.form.bonus090': '0.90 (1 year no claims)',
  'autoPage.form.bonus100': '1.00 (Reference coefficient)',
  'autoPage.form.bonus125': '1.25 (1 at-fault claim)',
  'autoPage.form.bonus150': '1.50 (2+ claims)',
  'autoPage.form.other': 'Other',
  'autoPage.learnMore': 'car insurance',
  'autoPage.readyToSave': 'car insurance',
  'autoPage.faq1.q': 'What is the difference between third-party and comprehensive insurance?',
  'autoPage.faq1.a': 'Third-party insurance only covers damage to others. Comprehensive insurance provides full protection including damage to your own vehicle.',
  'autoPage.faq2.q': 'How is the price of my car insurance calculated?',
  'autoPage.faq2.a': 'The rate depends on your age, how long you have held your licence, claims history, vehicle type and place of residence.',
  'autoPage.faq3.q': 'Can I cancel my car insurance at any time?',
  'autoPage.faq3.a': "Yes, under the Hamon law, you can cancel after one year of commitment, with no fees or penalties.",
  'autoPage.faq4.q': 'What is the no-claims bonus?',
  'autoPage.faq4.a': "It's a coefficient that varies your premium based on your driving history. Without an accident, you earn a 5% bonus per year.",

  // Santé Page
  'santePage.title': 'Health Insurance',
  'santePage.subtitle': 'Compare the best health plans and save up to €300 per year.',
  'santePage.adv1.title': 'Save up to €300',
  'santePage.adv1.desc': 'Compare and save on your health insurance.',
  'santePage.adv2.title': '20+ health plans compared',
  'santePage.adv2.desc': 'The best offers on the market.',
  'santePage.form.situation': 'Family situation',
  'santePage.form.single': 'Single',
  'santePage.form.couple': 'In a couple',
  'santePage.form.family': 'Family',
  'santePage.form.regime': 'Social security scheme',
  'santePage.form.regimeGeneral': 'General scheme',
  'santePage.form.alsace': 'Alsace-Moselle',
  'santePage.form.tns': 'Self-employed',
  'santePage.form.agricole': 'Agricultural',
  'santePage.form.level': 'Desired level of cover',
  'santePage.form.economique': 'Economy',
  'santePage.form.equilibre': 'Balanced',
  'santePage.form.confort': 'Comfort',
  'santePage.form.premium': 'Premium',
  'santePage.learnMore': 'health insurance',
  'santePage.readyToSave': 'health insurance',
  'santePage.faq1.q': "What's the difference between a mutuelle and complementary health insurance?",
  'santePage.faq1.a': 'Both terms refer to the same thing: a contract that supplements Social Security reimbursements for your healthcare costs.',
  'santePage.faq2.q': 'How does reimbursement work?',
  'santePage.faq2.a': 'After Social Security coverage, your health plan reimburses the remaining costs according to your contract guarantees (100%, 200%, etc. of the base rate).',
  'santePage.faq3.q': 'Can I switch health plans at any time?',
  'santePage.faq3.a': 'Yes, after one year of commitment, you can cancel without fees or justification thanks to the law of 14 July 2019.',
  'santePage.faq4.q': "What is the '100% Santé' scheme?",
  'santePage.faq4.a': "The '100% Santé' scheme provides access to glasses, dental prostheses and hearing aids with no out-of-pocket costs, if your plan is 'responsible'.",

  // Habitation Page
  'habitationPage.title': 'Home Insurance',
  'habitationPage.subtitle': 'Compare the best offers and save up to €300 per year.',
  'habitationPage.adv1.title': 'Save up to €300',
  'habitationPage.adv1.desc': 'Compare and save on your home insurance.',
  'habitationPage.adv2.title': '20+ insurers compared',
  'habitationPage.adv2.desc': 'The best offers on the market.',
  'habitationPage.form.type': 'Property type',
  'habitationPage.form.house': 'House',
  'habitationPage.form.apartment': 'Apartment',
  'habitationPage.form.status': 'You are',
  'habitationPage.form.owner': 'Owner',
  'habitationPage.form.tenant': 'Tenant',
  'habitationPage.form.surface': 'Area (m²)',
  'habitationPage.form.rooms': 'Number of rooms',
  'habitationPage.form.room1': '1 room',
  'habitationPage.form.room2': '2 rooms',
  'habitationPage.form.room3': '3 rooms',
  'habitationPage.form.room4': '4 rooms',
  'habitationPage.form.room5': '5 rooms or more',
  'habitationPage.form.value': 'Value of property to insure (€)',
  'habitationPage.learnMore': 'home insurance',
  'habitationPage.readyToSave': 'home insurance',
  'habitationPage.faq1.q': 'What are the essential guarantees?',
  'habitationPage.faq1.a': 'Fire, water damage, theft, civil liability and natural disasters are the basic guarantees.',
  'habitationPage.faq2.q': 'Should I insure my second home?',
  'habitationPage.faq2.a': "It's not mandatory except in co-ownership, but it's strongly recommended to protect your assets.",
  'habitationPage.faq3.q': 'What to do in case of a claim?',
  'habitationPage.faq3.a': 'Report the claim within 5 days (2 days for theft) to your insurer by registered letter.',
  'habitationPage.faq4.q': 'What is a deductible?',
  'habitationPage.faq4.a': "It's the amount you pay after compensation. The higher the deductible, the lower the premium.",

  // Moto Page
  'motoPage.title': 'Motorcycle Insurance',
  'motoPage.subtitle': 'Compare the best offers and save up to 35% on your motorcycle insurance.',
  'motoPage.adv1.title': 'Save up to 35%',
  'motoPage.adv1.desc': 'Compare and save on your motorcycle insurance.',
  'motoPage.adv2.title': '15+ insurers compared',
  'motoPage.adv2.desc': 'The best offers on the market.',
  'motoPage.form.brand': 'Motorcycle brand',
  'motoPage.form.brandPlaceholder': 'E.g.: Yamaha, Honda...',
  'motoPage.form.model': 'Model',
  'motoPage.form.modelPlaceholder': 'E.g.: MT-07, CBR...',
  'motoPage.form.type': 'Motorcycle type',
  'motoPage.form.roadster': 'Roadster',
  'motoPage.form.sportive': 'Sport',
  'motoPage.form.custom': 'Custom',
  'motoPage.form.trail': 'Trail',
  'motoPage.form.scooter': 'Scooter',
  'motoPage.form.displacement': 'Engine displacement (cc)',
  'motoPage.form.license': 'Date licence obtained',
  'motoPage.learnMore': 'motorcycle insurance',
  'motoPage.readyToSave': 'motorcycle insurance',
  'motoPage.faq1.q': 'What is the difference between third-party and comprehensive insurance?',
  'motoPage.faq1.a': 'Third-party insurance covers damage to others. Comprehensive also includes damage to your own motorcycle.',
  'motoPage.faq2.q': 'Is rider protection important?',
  'motoPage.faq2.a': 'Yes, it compensates you for injuries even if you are at fault in the accident.',
  'motoPage.faq3.q': 'Is my gear covered?',
  'motoPage.faq3.a': 'Some plans cover helmet, jacket and gloves. Check the reimbursement limits.',
  'motoPage.faq4.q': 'Can I insure a 50cc scooter?',
  'motoPage.faq4.a': 'Yes, insurance is mandatory for all motor vehicles, including 50cc scooters.',

  // Animaux Page
  'animauxPage.title': 'Pet Insurance',
  'animauxPage.subtitle': "Protect your pet's health and control your veterinary costs.",
  'animauxPage.adv1.title': 'Up to 100% reimbursed',
  'animauxPage.adv1.desc': 'The best veterinary reimbursement rates.',
  'animauxPage.adv2.title': '10+ insurers compared',
  'animauxPage.adv2.desc': 'The best pet insurance plans.',
  'animauxPage.form.animalType': 'Type of animal',
  'animauxPage.form.dog': 'Dog',
  'animauxPage.form.cat': 'Cat',
  'animauxPage.form.breed': 'Breed',
  'animauxPage.form.breedPlaceholder': 'E.g.: Labrador, Siamese...',
  'animauxPage.form.animalAge': "Pet's age",
  'animauxPage.form.sex': 'Sex',
  'animauxPage.form.male': 'Male',
  'animauxPage.form.female': 'Female',
  'animauxPage.form.sterilized': 'Spayed/Neutered',
  'animauxPage.form.yes': 'Yes',
  'animauxPage.form.no': 'No',
  'animauxPage.learnMore': 'pet insurance',
  'animauxPage.readyToSave': 'pet',
  'animauxPage.readyTitle': 'Ready to protect your pet?',
  'animauxPage.readyDesc': 'Compare the best pet insurance plans for free in 2 minutes.',
  'animauxPage.faq1.q': 'From what age can you insure your pet?',
  'animauxPage.faq1.a': 'From 2-3 months up to 8-10 years old for a first subscription.',
  'animauxPage.faq2.q': 'What is the waiting period?',
  'animauxPage.faq2.a': "The period after subscription during which you are not covered. A few days for accidents, a few months for illnesses.",
  'animauxPage.faq3.q': 'Are vaccinations reimbursed?',
  'animauxPage.faq3.a': 'Yes, with plans including a prevention allowance (vaccinations, wormers, antiparasitics).',
  'animauxPage.faq4.q': 'What if my pet has a pre-existing condition?',
  'animauxPage.faq4.a': 'Pre-existing conditions are generally excluded. Subscribe as early as possible.',

  // Toast messages
  'insPage.toast.success': 'Offers generated!',
  'insPage.toast.successDesc': 'Check out the best offers for your profile.',
  'insPage.toast.successDescHome': 'Check out the best offers for your property.',
  'insPage.toast.successDescMoto': 'Check out the best offers for your motorcycle.',
  'insPage.toast.successDescPet': 'Check out the best offers for your pet.',
  'insPage.toast.error': 'Error',
  'insPage.toast.errorDesc': 'An error occurred. Please try again.',
};

const translations: Record<Language, Record<string, string>> = { fr, en };

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    return saved && (saved === 'fr' || saved === 'en') ? saved : 'fr';
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = useCallback((key: string): string => {
    return translations[language][key] || translations['fr'][key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
