export interface RouteConfig {
  path: string;
  changefreq: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
  priority: number;
}

// Configuration centralisée de toutes les routes du site
export const SITE_URL = "https://www.jemassuremoinscher.fr";

// Pages principales
export const routes: RouteConfig[] = [
  // Homepage
  { path: "/", changefreq: "daily", priority: 1.0 },

  // Main Pages
  { path: "/comparateur", changefreq: "weekly", priority: 0.9 },
  { path: "/blog", changefreq: "daily", priority: 0.9 },
  { path: "/contact", changefreq: "monthly", priority: 0.7 },
  { path: "/qui-sommes-nous", changefreq: "monthly", priority: 0.6 },
  { path: "/nos-partenaires", changefreq: "monthly", priority: 0.6 },
  { path: "/avis-clients", changefreq: "weekly", priority: 0.8 },
  { path: "/assurance-expatries", changefreq: "weekly", priority: 0.85 },
  { path: "/gestion-locative", changefreq: "weekly", priority: 0.8 },
  { path: "/glossaire", changefreq: "weekly", priority: 0.8 },
  { path: "/plan-du-site", changefreq: "monthly", priority: 0.5 },
  { path: "/sources-et-methodologie", changefreq: "monthly", priority: 0.6 },

  // Insurance Product Pages - High Priority
  { path: "/assurance-auto", changefreq: "weekly", priority: 0.9 },
  { path: "/assurance-moto", changefreq: "weekly", priority: 0.9 },
  { path: "/assurance-habitation", changefreq: "weekly", priority: 0.9 },
  { path: "/assurance-sante", changefreq: "weekly", priority: 0.9 },
  { path: "/assurance-vie", changefreq: "weekly", priority: 0.9 },
  { path: "/assurance-pret", changefreq: "weekly", priority: 0.8 },
  { path: "/assurance-animaux", changefreq: "weekly", priority: 0.9 },
  { path: "/assurance-pno", changefreq: "weekly", priority: 0.7 },
  { path: "/assurance-gli", changefreq: "weekly", priority: 0.9 },
  { path: "/assurance-mrp", changefreq: "weekly", priority: 0.7 },
  { path: "/assurance-prevoyance", changefreq: "weekly", priority: 0.7 },
  { path: "/assurance-rc-pro", changefreq: "weekly", priority: 0.9 },
  { path: "/assurance-metiers-atypiques", changefreq: "weekly", priority: 0.9 },
  // Nouvelles verticales (pages complètes)
  { path: "/assurance-decennale", changefreq: "weekly", priority: 0.9 },
  { path: "/assurance-flotte-auto", changefreq: "weekly", priority: 0.9 },
  { path: "/assurance-mutuelle-entreprise", changefreq: "weekly", priority: 0.9 },
  { path: "/assurance-cyber", changefreq: "weekly", priority: 0.9 },
  { path: "/assurance-sans-permis", changefreq: "weekly", priority: 0.9 },
  { path: "/assurance-camping-car", changefreq: "weekly", priority: 0.9 },
  { path: "/assurance-velo", changefreq: "weekly", priority: 0.9 },
  { path: "/assurance-protection-juridique", changefreq: "weekly", priority: 0.9 },
  { path: "/assurance-auto-temporaire", changefreq: "weekly", priority: 0.9 },

  // SEO Pages
  { path: "/assurance-auto-malusse", changefreq: "weekly", priority: 0.8 },
  { path: "/assurance-auto-jeune-conducteur", changefreq: "weekly", priority: 0.8 },
  { path: "/mutuelle-tns", changefreq: "weekly", priority: 0.8 },
  { path: "/assurance-auto-comparatif", changefreq: "weekly", priority: 0.8 },
  { path: "/assurance-trottinette-electrique", changefreq: "weekly", priority: 0.9 },
  { path: "/assurance-trottinette-livreur", changefreq: "weekly", priority: 0.85 },

  { path: "/assurance-auto-permis-etranger", changefreq: "weekly", priority: 0.8 },
  { path: "/assurance-emprunteur", changefreq: "weekly", priority: 0.8 },

  // Profils Spéciaux
  { path: "/profil", changefreq: "weekly", priority: 0.8 },
  { path: "/profil/resilie-non-paiement", changefreq: "weekly", priority: 0.8 },
  { path: "/profil/retrait-permis", changefreq: "weekly", priority: 0.8 },
  { path: "/profil/frequence-sinistres", changefreq: "weekly", priority: 0.8 },
  { path: "/profil/sans-antecedents", changefreq: "weekly", priority: 0.8 },
  // /profil/jeune-conducteur-voiture-puissante: 301 → /blog/jeune-conducteur-voiture-puissante-110-chevaux (consolidated to avoid cannibalization)
  { path: "/profil/fausse-declaration", changefreq: "weekly", priority: 0.8 },
  { path: "/profil/malus-eleve", changefreq: "weekly", priority: 0.8 },
  { path: "/profil/permis-etranger", changefreq: "weekly", priority: 0.8 },
  { path: "/profil/senior-75-plus", changefreq: "weekly", priority: 0.8 },
  { path: "/profil/voiture-collection", changefreq: "weekly", priority: 0.8 },
  { path: "/profil/vehicule-importe", changefreq: "weekly", priority: 0.8 },
  { path: "/profil/chauffeur-vtc-taxi", changefreq: "weekly", priority: 0.8 },
  { path: "/profil/alcoolemie-stupefiants", changefreq: "weekly", priority: 0.8 },
  { path: "/profil/delit-de-fuite", changefreq: "weekly", priority: 0.8 },

  // Comparatifs / Duels
  { path: "/comparatif", changefreq: "weekly", priority: 0.8 },
  { path: "/comparatif/maif-vs-macif", changefreq: "monthly", priority: 0.7 },
  { path: "/comparatif/axa-vs-allianz", changefreq: "monthly", priority: 0.7 },
  { path: "/comparatif/amv-vs-maaf", changefreq: "monthly", priority: 0.7 },
  { path: "/comparatif/direct-assurance-vs-l-olivier", changefreq: "monthly", priority: 0.7 },
  { path: "/comparatif/luko-vs-alan", changefreq: "monthly", priority: 0.7 },
  { path: "/comparatif/groupama-vs-gmf", changefreq: "monthly", priority: 0.7 },
  { path: "/comparatif/matmut-vs-mma", changefreq: "monthly", priority: 0.7 },
  { path: "/comparatif/maaf-vs-matmut", changefreq: "monthly", priority: 0.7 },
  { path: "/comparatif/generali-vs-axa", changefreq: "monthly", priority: 0.7 },
  { path: "/comparatif/april-vs-alan", changefreq: "monthly", priority: 0.7 },
  { path: "/comparatif/swiss-life-vs-generali", changefreq: "monthly", priority: 0.7 },
  { path: "/comparatif/abeille-vs-groupama", changefreq: "monthly", priority: 0.7 },
  { path: "/comparatif/alan-vs-harmonie-mutuelle", changefreq: "monthly", priority: 0.7 },

  // Outils
  { path: "/outils/calculateur-bonus-malus", changefreq: "monthly", priority: 0.7 },

  // Landing Pages
  { path: "/landing/assurance", changefreq: "weekly", priority: 0.8 },
  { path: "/landing/auto-entrepreneur", changefreq: "weekly", priority: 0.7 },
  { path: "/landing/senior", changefreq: "weekly", priority: 0.7 },
  { path: "/landing/scooter", changefreq: "weekly", priority: 0.7 },
  { path: "/landing/rc-pro-micro-entreprise", changefreq: "weekly", priority: 0.7 },
  { path: "/landing/restaurant", changefreq: "weekly", priority: 0.7 },
  { path: "/landing/photographe", changefreq: "weekly", priority: 0.7 },
  { path: "/landing/influenceur", changefreq: "weekly", priority: 0.7 },
  { path: "/landing/accrobranche", changefreq: "weekly", priority: 0.7 },
  { path: "/landing/evenementiel", changefreq: "weekly", priority: 0.7 },
  { path: "/landing/cordiste-btp", changefreq: "weekly", priority: 0.7 },
  { path: "/landing/moniteur-sport", changefreq: "weekly", priority: 0.7 },

  // Legal Pages
  { path: "/mentions-legales", changefreq: "yearly", priority: 0.3 },
  { path: "/politique-confidentialite", changefreq: "yearly", priority: 0.3 },
  { path: "/politique-cookies", changefreq: "monthly", priority: 0.5 },
  { path: "/cgu", changefreq: "yearly", priority: 0.3 },
];

// Blog articles — all slugs from blogArticles.ts + blogArticles2026.ts
// IMPORTANT: Keep in sync with actual slug values in blogArticles.ts & blogArticles2026.ts
export const blogArticles: RouteConfig[] = [
  // === blogArticles.ts (legacy + 2025→2026 updated) ===
  { path: "/blog/mutuelle-sante-reduire-frais-medicaux-2026", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/assurance-auto-jeune-conducteur-astuces", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/resiliation-assurance-droits-2026", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/loi-lemoine-assurance-emprunteur-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/loi-hamon-resiliation-assurance", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/guide-choisir-assurance-auto-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/assurance-habitation-garanties-indispensables", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/10-conseils-economiser-assurances", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/bien-choisir-mutuelle-sante", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/meilleure-assurance-auto-2026-comparatif", changefreq: "monthly", priority: 0.9 },
  { path: "/blog/top-10-meilleures-mutuelles-sante-2026", changefreq: "monthly", priority: 0.9 },
  { path: "/blog/assurance-jeune-conducteur-2026-moins-cher", changefreq: "monthly", priority: 0.9 },
  
  { path: "/blog/top-mutuelles-sante-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/comparatif-habitation-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/loi-lemoine-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/nouvelle-reglementation-assurance-2026", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/droits-des-assures-2026", changefreq: "monthly", priority: 0.7 },

  // === blogArticles2026.ts ===
  { path: "/blog/assurance-auto-resiliation-non-paiement-guide", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/jeune-conducteur-voiture-puissante-110-chevaux", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/assurance-malus-eleve-compagnies-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/seniors-75-ans-assurance-auto-prime-basse", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/permis-conduire-etranger-assurance-auto-france", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/assurance-auto-resilie-alcool-stupefiants", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/conducteur-secondaire-assurance-auto-bonne-idee", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/top-10-voitures-occasion-moins-cheres-assurer-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/assurance-au-kilometre-pay-as-you-drive-rentable", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/supprimer-options-inutiles-contrat-habitation", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/franchise-elevee-prime-basse-simulateur-choix", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/regrouper-contrats-auto-maison-reduction-reelle", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/assurance-auto-connectee-boitiers-intelligents-prix", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/hausse-tarifs-assurance-2026-comment-contrer", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/demenagement-prevenir-assureur-couverture", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/assurance-colocation-contrat-unique-ou-individuel", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/teletravail-assurance-habitation-materiel-pro-couvert", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/sous-location-airbnb-risques-caches-assurance", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/assurance-panneaux-photovoltaiques-installation", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/degat-des-eaux-voisins-constat-amiable-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/assurance-pno-obligatoire-louer-bien", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/assurance-voiture-electrique-bonus-ecologiques-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/trottinettes-electriques-edpm-assurance-obligatoire", changefreq: "monthly", priority: 0.85 },
  { path: "/blog/assurance-trottinette-vol-garantie-2026", changefreq: "monthly", priority: 0.85 },
  { path: "/blog/trottinette-electrique-debridage-loi-risques-2026", changefreq: "monthly", priority: 0.85 },
  { path: "/blog/assurance-trottinette-livreur-uber-eats-deliveroo-2026", changefreq: "monthly", priority: 0.9 },
  { path: "/blog/trottinette-electrique-accident-sinistre-demarches-2026", changefreq: "monthly", priority: 0.85 },
  { path: "/blog/assurance-gyroroue-hoverboard-monoroue-edpm-2026", changefreq: "monthly", priority: 0.85 },
  { path: "/blog/comparatif-assurance-trottinette-electrique-2026", changefreq: "monthly", priority: 0.9 },

  { path: "/blog/velos-cargos-vae-protection-vol-urbain", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/recharge-domicile-assurance-borne-recharge", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/covoiturage-regulier-extension-garantie-passagers", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/loi-hamon-2026-resilier-assurance-3-clics", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/vente-vehicule-suspendre-assurance-jour-j", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/certificat-assurance-dematerialise-fin-vignette-verte", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/non-lieu-assurance-aucun-assureur-role-bct", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/voiture-immobilisee-garage-arreter-assurer", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/heritage-vehicule-assurer-voiture-deces", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/reste-a-charge-zero-100-sante-lunettes-dents-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/mutuelle-etudiante-contrat-parents-ou-individuel", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/auto-entrepreneur-mutuelle-protection-optimale", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/assurance-emprunteur-changer-gagner-milliers-euros", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/medecines-douces-mutuelles-osteopathie-hypnose", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/fausse-declaration-assurance-risques-reels", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/5-arnaques-assurance-courantes-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/accident-seul-sans-tiers-declarer-reparer", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/hypnose-remboursement-mutuelle-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/devis-assurance-auto-jeune-conducteur-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/assurance-pno-pas-chere-comparatif-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/assurance-parc-accrobranche-obligations-2026", changefreq: "monthly", priority: 0.9 },
  { path: "/blog/assurance-moniteur-sports-outdoor-2026", changefreq: "monthly", priority: 0.9 },
  { path: "/blog/assurance-organisateur-evenement-festival-2026", changefreq: "monthly", priority: 0.9 },

  // === Série Expatriés 2026 (15 articles) ===
  { path: "/blog/assurance-auto-expatries-france", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/assurance-habitation-expatries", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/mutuelle-sante-expatries-france", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/changer-assurance-expatrie", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/assurance-couples-mixtes-france", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/assurance-etudiant-etranger-france", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/cotisations-sociales-assurance-expatrie", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/rapatriement-assurance-expatries", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/temoignages-expatries-assurance", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/assurance-expat-france-vs-origine", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/visa-long-sejour-assurance-france", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/assurance-tech-workers-expatries", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/assurance-cadres-expatries-mutation", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/assurance-retraite-expatrie-france", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/assurance-frontalier-france", changefreq: "monthly", priority: 0.7 },

  // Niches spécialisées 2026
  { path: "/blog/assurance-auto-malus-eleve-crm", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/assurance-jeune-conducteur-sans-experience", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/assurance-auto-vintage-collection", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/assurance-auto-teletravail-peu-kilometrage", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/assurance-auto-apres-retrait-permis", changefreq: "monthly", priority: 0.7 },
  { path: "/blog/assurance-habitation-zone-inondable-sinistre", changefreq: "monthly", priority: 0.7 },

  // === Série Verticales 2026 (Décennale, Flotte auto, Mutuelle entreprise) ===
  { path: "/blog/garantie-decennale-2026-guide-complet-artisans-btp", changefreq: "monthly", priority: 0.9 },
  { path: "/blog/rc-pro-decennale-differences-artisans-btp", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/decennale-auto-entrepreneur-btp-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/assurance-flotte-auto-2026-guide-entreprise", changefreq: "monthly", priority: 0.9 },
  { path: "/blog/boitiers-connectes-flotte-auto-entreprise-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/reduire-cout-flotte-auto-entreprise-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/mutuelle-entreprise-2026-guide-complementaire-sante-collective", changefreq: "monthly", priority: 0.9 },
  { path: "/blog/mutuelle-tns-vs-mutuelle-entreprise-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/surcomplementaire-sante-entreprise-2026", changefreq: "monthly", priority: 0.8 },
  // Verticales 2026 - Lot 2 (Cyber, Sans permis, Camping-car)
  { path: "/blog/assurance-cyber-2026-guide-entreprise", changefreq: "monthly", priority: 0.9 },
  { path: "/blog/ransomware-5-reflexes-eviter-pire-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/rgpd-fuite-donnees-assurance-cyber-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/assurance-voiture-sans-permis-2026-guide", changefreq: "monthly", priority: 0.9 },
  { path: "/blog/vsp-ado-14-ans-permis-am-assurance-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/vsp-suspension-permis-assurance-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/assurance-camping-car-2026-guide-complet", changefreq: "monthly", priority: 0.9 },
  { path: "/blog/van-amenage-assurance-2026", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/camping-car-hivernage-assurance-2026", changefreq: "monthly", priority: 0.8 },
];

// Glossary terms
export const glossaryTerms: RouteConfig[] = [
  { path: "/glossaire/franchise", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/prime-assurance", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/sinistre", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/bonus-malus", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/indemnisation", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/tiers", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/tous-risques", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/constat-amiable", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/loi-hamon", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/loi-lemoine", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/mutuelle-sante", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/ticket-moderateur", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/tiers-payant", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/responsabilite-civile", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/assurance-emprunteur", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/degat-des-eaux", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/garantie-decennale", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/assurance-pno", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/garantie-loyers-impayes", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/rc-pro", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/prevoyance", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/vetuste", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/delai-de-carence", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/avenant", changefreq: "monthly", priority: 0.7 },
  { path: "/glossaire/assurance-vie", changefreq: "monthly", priority: 0.7 },
];
